### ISSUE TITLE
epicMiddleware.replaceEpic(nextEpic) adds nextEpic instead of replacing

### ISSUE THREAD

**Issue by rochdev** [redux-observable/redux-observable#112]
To reproduce, simply call `epicMiddleware.replaceEpic(nextEpic)` mutiple times. All actions then get received multiple times by your epics.

**Comment by jayphelps** [comment]
Yikes! What version log redux-observable? Has this always happened or just broke in 0.10.0?

**Comment by rochdev** [comment]
We are using 0.10.0. I don't know about previous versions since we started using redux-observable this week.

However, looking at the code of `replaceEpic` it seems to call `BehaviorSubject.next` with the new epic which is basically what the docs says to do when you want to add an epic to existing epics (https://redux-observable.js.org/docs/recipes/AddingNewEpicsAsynchronously.html). We are pretty new to RxJS and observables in general so sorry if this is not accurate.

**Comment by jayphelps** [comment]
@rochdev It all seems to be working as expected for me: https://jsbin.com/vayoho/edit?js,console You'll see in the console that the epic receives the `EPIC_END` action signal and then immediately after it terminates, the new epic then starts taking actions.

Could you perhaps modify that JSBin or otherwise provide a way to reproduce your problem? My initial best guess is that you might have something inside your epic that is preventing itself from being shut down, even though our middleware is no longer subscribing to it.

***

Regarding our use of `BehaviorSubject`, we're using `switchMap` which switches between the existing root epic and the incoming new one, shutting down the old by unsubscribing (assuming your epics are well behaved). The "Adding New Epics Async" doc example uses `mergeMap` instead, which as you might guess doesn't _switch_ between incoming streams, it _merges_ them so they'll accumulate (as intended for that use case).

**Comment by rochdev** [comment]
Ok it seems it was caused by a misunderstanding of the library. I updated the JSBin to showcase what I was doing wrong in my tests (even though I don't fully understand this behaviour yet).

Thank you for the thorough explanation!

**Comment by jayphelps** [comment]
@rochdev when you edit someone elses JSBin, it automatically clones it btw--so I can't see the changes you made. Not a problem, unless you _wanted_ me to look at them of course!

Lmk if I can help further! 😄
