### ISSUE TITLE
Compatability with thunk

### ISSUE THREAD

**Issue by e-schultz** [redux-observable/redux-observable#13]
Currently both redux-observable and thunk are doing a `typeof action === 'function'` - was wondering if taking a cue from [redux-rxjs](https://github.com/acdlite/redux-rx/blob/master/src/observableMiddleware.js#L7) and checking if the action is an observable instead of just a function would allow for this to be compatible with thunk?

Or is there something else going on due to the support for teardown/cancelling an observable that I'm missing that wouldn't allow this to be possible?

**Comment by jayphelps** [comment]
(not sure if you missed it or not, but this is [mentioned in the README](https://github.com/blesh/redux-observable#incompatible-w-redux-thunk))

There isn't any way to support both AFAIK because we can't check for Observable because that's not what you dispatch, you dispatch a function, just like redux-thunk dispatches functions, the difference being that the signature our middleware invokes that function with its `fn(actions: ActionsObservable, store: Store)` where as redux-thunk invokes the functions as `fn(dispatch: Function, getState: Function)`.  This factory style is crucial, because actions need to be able to receive an stream of all future actions, `ActionsObservable`, so that they can `takeUntil` (aka cancelling) and do other composition.

If you can think of an alternative that doesn't involve globals, do let us know.

**Comment by jayphelps** [comment]
I guess it's technically possible we could switch to `fn(dispatch, getState, actions)` and then do `fn.length` to see if they provided 3 different args as our check, then swallow that action (just like today) instead of passing it along to redux-thunk. But since direct dispatch is totally an antipattern with redux-observable that's mostly out of the question just to support compatibility with redux-thunk. It's also rather brittle and ugly, obviously.

**Comment by e-schultz** [comment]
True,

Was just thinking about existing applications that were using thunk, but I guess it wouldn't be too much work to refactor the action creators that were relying on dispatch to play nicely with this instead.

**Comment by blesh** [comment]
We could get it to be a stand-in replacement for thunk if we changed the order and types of arguments we pass to the dispatched function. `(dispatch, getState, actions) => Observable...`

It would be a breaking change, of course. And we always return a subscription, so that wouldn't necessarily be compatible with existing thunk use

**Comment by jayphelps** [comment]
Yeah, I mentioned that here:

> I guess it's technically possible we could switch to fn(dispatch, getState, actions) and then do fn.length to see if they provided 3 different args as our check, then swallow that action (just like today) instead of passing it along to redux-thunk. But since calling dispatch() directly is totally an antipattern with redux-observable that's mostly out of the question just to support compatibility with redux-thunk. It's also rather brittle and ugly, obviously.

People can port to redux-observable with simply find-and-replace:

```
s/dispatch, getState/_, { dispatch, getState }
```

e.g.

```js
(dispatch, getState) => {};
// becomes
(_, { dispatch, getState }) => {};
```
Because first argument is the `ActionsObservable` that they can just ignore (hence `_` param name) and second argument is the redux store, which they can destructure to `{ dispatch, getState }` and boom, their function body doesn't need to be touched.

I'm personally 👎 since it's fairly trivial for someone to port their redux-thunk actions to redux-observable, but making our signatures like that _just to make transitions easier_ at the expense making thunkservables ergonomics awkward is not nice. e.g. AFAICT it's an antipattern to call `dispatch` in a true thunkservable, your observable should just emit it.

Counter thoughts?

**Comment by jayphelps** [comment]
I forgot that we currently **require** that your thunk returns something that can be consumed by `Observable.from`. So if you don't return anything compatibile (not an observable, promise, iterable, etc) then you'll get `Uncaught TypeError: WHATEVER is not observable`.

I think to make the transition as I described above easier, (and just generally make the API more ergonomic) we might consider somehow handling that case more gracefully and instead just returning the value they returned, if we cannot consume it as an observable. The only negative I can think of that approach is that if they actually did intend to return an observable (as is the case, usually) but they have a bug, we'll no longer provide them with an error so it may "fail" silently and be harder to debug. hmmm.

**Comment by e-schultz** [comment]
@jayphelps thanks for the insight on the challenges around it. Considering how easy it should be for most things to get changed to work with redux-observable, adding something that is brittle and an anti-pattern into this library just for transitional support doesn't seem like the best idea.
