### ISSUE TITLE
How do observable epics relate to epimorphism

### ISSUE THREAD

**Issue by leshow** [redux-observable/redux-observable#135]
I have a basic understanding of monomorphism, epimorphism, and a few other category theory concepts like monoids and monads.

Im trying to figure out what exactly makes observables here epic, and why the term was borrowed. Itd be great if the readme or FAQ said that somewhere, since you use the term quite a bit.

I understand that epimorphism in Set is injective. Is that what you're getting at with "epic"?

**Comment by jayphelps** [comment]
The short answer is that our usage of the term "epic" is unrelated to epimorphism or anything in category theory. It was chosen in relation to the "saga", because the pattern is similar to redux-saga, but we felt the term saga was [not actually correct](http://kellabyte.com/2012/05/30/clarifying-the-saga-pattern/) primarily because sagas are not supposed to maintain any state. (saga, epic, myth, legend, all story related in English)

> The pattern of handling side effects this way is similar to the "process manager" pattern, sometimes called a "saga", but the original definition of saga is not truly applicable. If you're familiar with redux-saga, redux-observable is very similar. But because it uses RxJS it is much more declarative and you utilize and expand your existing RxJS abilities. -[Docs](https://redux-observable.js.org/docs/basics/Epics.html)

We didn't feel there was a need to clarify it not having relation to an epi, since it's not well known in JavaScript circles and could introduce unnecessary confusion.

**Comment by leshow** [comment]
Ah ok, thanks for the answer. I was wracking my brain trying to figure out how such a thing could be epic as in "epimorphism".
