### ISSUE TITLE
Hot Module Replacement repeats all actions?

### ISSUE THREAD

**Issue by BerndWessels** [redux-observable/redux-observable#142]
Hi,

is it correct behavior that all previous actions get repeated whenever a hot reload happens?

And if so, is there a way to turn that off?

`redux-observable 0.12.1`

I debugged it and it is definitely triggered by the hot reload, not by my code.

**Comment by jayphelps** [comment]
Have you seen our docs on this? https://redux-observable.js.org/docs/recipes/HotModuleReplacement.html

> Replacing Epics that were already running with a new version can potentially create strange bugs because Epics naturally may maintain some internal state or depend on some external transient state or side effect. Think about how debouncing keeps track, or more insidious before you kick off an AJAX request you put the store into a pending state. This is not unique to redux-observable; every alternative middleware we know of has this problem because it's inherent to the nature of handling side effects.

You can prevent it by not using hot reloading on your epics themselves--but feel free to continue to hot reload your reducers or components. If the issue exists and you're not hot reloading your epics, the problem is definitely not related to redux-observable, but I can try to possibly guess at what it might be if you provide more quite a bit of info about your setup. build pipeline, babel plugins, what is doing the reloading, the code that _is_ doing hot reloading, etc.

**Comment by jayphelps** [comment]
Actually, sorry bout that, I think I misunderstood what you mean. You're saying all previous actions literally get re-dispatched? Your epics receive them and your reducers receive them all again one after the other? This shouldn't be happening, I would definitely need a reproducible example to help. redux-observable does not keep a history of actions so it's not possible for _itself_ to be the culprit.

**Comment by BerndWessels** [comment]
@jayphelps Hi, thanks for the quick reply.

Yes, I make a change in a component and `hot module reloading` happens. This then for a magical reason re-dispatches all `actions` that have been done before even in the same order.

```
@@INIT
component.js?a623:39Call initializeClient only once when client starts!
reducer.js?2e98:64ROOT_INITIALIZE_CLIENT
reducer.js?2e98:64ROOT_FETCH_GRAPHQL_SCHEMA
reducer.js?2e98:64ROOT_FETCH_GRAPHQL_SCHEMA_PENDING
client.js?3ac5:58[HMR] connected
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_SCHEMA_SUCCEEDED
reducer.js?2e98:64 PING
reducer.js?2e98:64 PONG
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_QUERY
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_QUERY_PENDING
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_QUERY_SUCCEEDED
client.js?3ac5:128 [HMR] bundle rebuilding
client.js?3ac5:132 [HMR] bundle rebuilt in 850ms
process-update.js?e13e:27 [HMR] Checking for updates on the server...
reducer.js?2e98:64 @@INIT
reducer.js?2e98:64 ROOT_INITIALIZE_CLIENT
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_SCHEMA
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_SCHEMA_PENDING
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_SCHEMA_SUCCEEDED
reducer.js?2e98:64 PING
reducer.js?2e98:64 PONG
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_QUERY
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_QUERY_PENDING
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_QUERY_SUCCEEDED
reducer.js?2e98:64 @@redux-observable/EPIC_END
process-update.js?e13e:100 [HMR] Updated modules:
process-update.js?e13e:102 [HMR]  - ./src/app/counter/component.js
process-update.js?e13e:102 [HMR]  - ./src/app/counter/index.js
process-update.js?e13e:102 [HMR]  - ./src/app/component.js
process-update.js?e13e:102 [HMR]  - ./src/reducer.js
process-update.js?e13e:102 [HMR]  - ./src/app/index.js
process-update.js?e13e:102 [HMR]  - ./src/component.js
process-update.js?e13e:102 [HMR]  - ./src/epic.js
process-update.js?e13e:107 [HMR] App is up to date.
```

I have a little boilerplate project which you can find here [https://github.com/BerndWessels/react-redux-rr4-wp2-rhl3](https://github.com/BerndWessels/react-redux-rr4-wp2-rhl3).

It is easy to reproduce:
1. Clone the repo
2. `npm install`
3. `npm start`
4. Browse to `http://localhost:8080`
5. You might have to reload a few times in the beginning since the project calls a GraphQL endpoint hosted in an AWS Lambda function which needs to wake up first.
6. Press the `Ping` button.
7. Now you should see
```
@@INIT
component.js?a623:39Call initializeClient only once when client starts!
reducer.js?2e98:64ROOT_INITIALIZE_CLIENT
reducer.js?2e98:64ROOT_FETCH_GRAPHQL_SCHEMA
reducer.js?2e98:64ROOT_FETCH_GRAPHQL_SCHEMA_PENDING
client.js?3ac5:58[HMR] connected
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_SCHEMA_SUCCEEDED
reducer.js?2e98:64 PING
reducer.js?2e98:64 PONG
```
8. When you then change for example the `<h1>Counter</h1>` in `line 36` in file `/react-redux-rr4-wp2-rhl3/src/app/counter/component.js` to `<h1>Counter Bla</h1>` and save the file the `hot module reloading` happens and you will see
```
client.js?3ac5:128 [HMR] bundle rebuilding
client.js?3ac5:132 [HMR] bundle rebuilt in 850ms
process-update.js?e13e:27 [HMR] Checking for updates on the server...
reducer.js?2e98:64 @@INIT
reducer.js?2e98:64 ROOT_INITIALIZE_CLIENT
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_SCHEMA
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_SCHEMA_PENDING
reducer.js?2e98:64 ROOT_FETCH_GRAPHQL_SCHEMA_SUCCEEDED
reducer.js?2e98:64 PING
reducer.js?2e98:64 PONG
reducer.js?2e98:64 @@redux-observable/EPIC_END
process-update.js?e13e:100 [HMR] Updated modules:
process-update.js?e13e:102 [HMR]  - ./src/app/counter/component.js
process-update.js?e13e:102 [HMR]  - ./src/app/counter/index.js
process-update.js?e13e:102 [HMR]  - ./src/app/component.js
process-update.js?e13e:102 [HMR]  - ./src/reducer.js
process-update.js?e13e:102 [HMR]  - ./src/app/index.js
process-update.js?e13e:102 [HMR]  - ./src/component.js
process-update.js?e13e:102 [HMR]  - ./src/epic.js
process-update.js?e13e:107 [HMR] App is up to date.
```

So you can see that the `hot module reloading` actually re-dispatches all the actions again even in the right order and even the ones you caused by pressing on the `Ping` button.

Would you be so kind and have a look what is wrong here? Maybe I am doing something wrong in my `epics`? Or is there actually a bug in `redux-observable`?

Thank you very much.

**Comment by jayphelps** [comment]
Ok, so the issue is complex.

* Your epics are _not_ receiving the same actions again--only your reducers.
  * Your reducers are receiving the same actions again because this is what happens (expected) when your reducers are hot reloaded and you're have the redux-devtools extension installed. The devtools extension itself is the one who is replaying them to your reducers. This can be turned off with the [`shouldHotReload` option](https://github.com/zalmoxisus/redux-devtools-extension/blob/a37c0ef23a865e58c928eb21e58b1252dd3e77fc/docs/API/Arguments.md) but be careful, it's on by default probably for a reason.
* Your reducers and epics are being hot reloaded every time you edit that component because of complex import dependencies that are not immediately obvious. It may be some what related to the fact that you import both the reducer and component into [the same `index.js`](https://github.com/BerndWessels/react-redux-rr4-wp2-rhl3/blob/master/src/app/counter/index.js#L13-L14) file and then consumers of either import that file, so HMR connects the component module to the reducer module, which is then imported by other dependencies which also import the [`app/index.js`](https://github.com/BerndWessels/react-redux-rr4-wp2-rhl3/blob/master/src/app/index.js#L13-L15) which imports the root epic, reducer, and component as well. This makes nearly everything dependent on everything else, so when a change is detected, it has to hot reload all of them to be safe.
* I also found that your app does not work with the redux devtools not enabled because you are relying on a global variable [compose](https://github.com/BerndWessels/react-redux-rr4-wp2-rhl3/blob/master/src/root.client.js#L37) that you should instead `import { compose } from 'redux';`
  * It's not immediately clear _why_ this works when the devtools are enabled, but it does. It doesn't appear to be a true `window.compose` variable, but I don't have time to dig further.

**Comment by jayphelps** [comment]
I'm very confident this is unrelated to redux-observable because of the aforementioned description as well as if you remove redux-observable, the problem persists.

That said, I'm happy to provide more help--if you have specific questions. Solving this seems to mostly be simplifying your import dependency pattern, or not using hot reloading (obviously). You might consider taking a look at how other developers are structuring their modules, e.g. the [redux examples](https://github.com/reactjs/redux/tree/master/examples) or the [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example)

**Comment by BerndWessels** [comment]
Wow, thank you so much @jayphelps for the detailed research. I am pretty sure that will help me sort everything out.
Love your work and tech talks.
Thanks from New Zealand

**Comment by jayphelps** [comment]
@BerndWessels you're very welcome! 🤘
