### ISSUE TITLE
ES Modules

### ISSUE THREAD

**Issue by Shyam-Chen** [redux-observable/redux-observable#166]
like `@reactivex/rxjs/dist/es6`

```js
import { partition } from 'lodash-es';
import { Observable } from 'rxjs/Observable';  // `rxjs` call `@reactivex/rxjs/dist/es6`
import { createStore } from 'redux';
```

**Comment by jayphelps** [comment]
No current plans. FWIW rxjs [no longer supports es modules](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#breaking-changes-2) either ever since rc.1, although they [accidentally snuck back](https://github.com/ReactiveX/rxjs/issues/2177#issuecomment-268368699) into the dist directory, don't rely on it.

Both redux-observable and rxjs do not receive any tangible benefit from publishing an es module version, why is [described here](https://github.com/ReactiveX/rxjs/issues/1671#issuecomment-252129235) but tl;dr operators are on the `Observable.prototype` so they cannot be tree shaked.

That said, on the rxjs side we're still planning to release an es module version at some point once the kinks are flushed out, simply so people don't keep asking us for it--even if there's no real benefit. 😆 

On the redux-observable side, it's mostly just prioritizing time..I don't have the cycles to do it at the moment and not much demand. Hope this makes sense!

**Comment by Shyam-Chen** [comment]
I hope support ES modules! I don't know how to bundle with Rollup. :sob:

**Comment by Shyam-Chen** [comment]
Sorry, I will copy your source code.  :scream:

**Comment by Shyam-Chen** [comment]
@jayphelps Can the source code be put on npm?

**Comment by Shyam-Chen** [comment]
https://github.com/Shyam-Chen/Rollducks

I released a simple version of ES.

**Comment by jayphelps** [comment]
@Shyam-Chen hehe you could PR the ability upstream 😉

**Comment by Shyam-Chen** [comment]
I found `@reactivex/rxjs/dist/es6` has not published. :sob: :sob: :sob:
