### ISSUE TITLE
not all of the methods from observable mapped?

### ISSUE THREAD

**Issue by kanekotic** [redux-observable/redux-observable#168]
This is actually a question as i am new to redux-observable (and also to react, hence redux, hence rxjs). 

I am trying to do a ticking mechanism on an epic and i kind of found a neat solution around by using `interval`.
```js
import 'rxjs'
import * as types from '../actions/types'
import Rx from 'rxjs/Rx';
var pauser = new Rx.Subject();

export function inStartRun(action$){
  return action$.ofType(types.START_RUN)
    .interval(1000)
    .map(function () { console.log('tick...') })
    .share()
    .pausable(pauser)
    .mapTo({ type: types.STOP_RUN});
}
```

but i am getting an error 
```
action$.ofType(...).interval is not a function
```

I have tried adding it manually as you se also in the snipped adding the global import, etc. And i cannot make it work. Shouldnt the observable have the same capabilities as the Rx.Obserbable?

either from my mind is not mapped, or i am doing something fundamentally wrong as if its a stream it expects only one action and not a recursion of actions being fired periodically (hence interval, timer, etc don't make sense for redux-observable).

**Comment by jayphelps** [comment]
Hey @kanekotic `interval` is a static operator, so it's only available on `Observable.interval` not as an instance method, `Observable.prototype.interval`. That is because it can only be used to _create_ an observable, not as a transformation to another source--it doesn't do any transforming.

I'm guessing instead you want to either merge or switch map into a new interval observable. Something _like_:

```js
export function inStartRun(action$){
  return action$.ofType(types.START_RUN)
    .switchMap(function () {
      Rx.Observable.interval(1000)
        .map(function () { console.log('tick...') })
        .share()
        .pausable(pauser)
        .mapTo({ type: types.STOP_RUN})
    });
}
```

But you'll then discover more problems. redux-observable uses RxJS v5 by default which does not have the `pausable()` operator that v4 did. If you found it recently by reading documentation somewhere, make sure you're reading v5 docs. If you'd rather use v4, you can [use an adapter here](https://github.com/redux-observable/redux-observable-adapter-rxjs-v4).

Also, you should do your `console.log('tick...')` in a `.do()`, which is used to make side effects which have no impact on the stream (logging being one example).

```js
.do(function () { console.log('tick...') })
```

Your current usage of `.map(function () { console.log('tick...') })` means you're mapping to `undefined`, which will cause redux to produce errors about invalid actions being dispatched.

***

Generally we ask that questions not be asked in the issue tracker. [StackOverflow](http://stackoverflow.com/questions/tagged/redux-observable) is a better forum for getting help, and we also have a [Gitter channel](https://gitter.im/redux-observable/redux-observable).

**Comment by kanekotic** [comment]
@jayphelps thanks a lot is a top notch answer. and excuse me for placing it in the wrong place.
