### ISSUE TITLE
Feature Request? Epics that don't return an action

### ISSUE THREAD

**Issue by gregkopp** [redux-observable/redux-observable#169]
According to the documentation, all Epics must return an action. However, there are situations where it is desirable for an Epic to not return a new action. I am writing a small application, as a learning tool for TypeScript, Angular2 and ng2-redux. Here is a snippet of code where I would NOT want an Epic to return a new action:

```
/// ElephantEpics.ts

	loadData = (action$: ActionsObservable<any>): any => {
		return action$.ofType(ElephantActions.LOAD_DATA)
			.map((action: any): Action => {
				this.load()
					.subscribe((response: any) => {
						this.actions.loadSucceeded(response);
					}, (err: any) => {
						this.actions.loadFailed(err);
					});
				return ({ type: 'NOOP'});
			});
	}

	private load(): any {
		let token = this.tokenServ.getToken();
		return this.service.getAll(token)
			.map(items => items)
			.catch(err => Observable.of(err));
	}

```
```
// ElephantService.ts

	getAll(token: string): Observable<{ ids: number[], entities: { [id: number]: Elephant } }> {
		return this.http.get(this.url, this.headers(token))
			.map((resp: Response) => resp.json())
			.map((items: Elephant[]) => this.getEntity(items))
			.catch((err: any) => Observable.throw(JSON.parse(err._body)))
	}

```

As you can see, I am creating an Epic that listens for a LOAD_DATA action and then calls a load function, which in turn calls a service to retrieve the data from the Elephants REST API. However, because I am subscribing to the Observable of the service call in order to call the appropriate actions to update the state via the reducer, I have to shoehorn in a 'NOOP' action to satisfy the return object.

Is there no way to have an Epic that does NOT return a new Action?

**Comment by jayphelps** [comment]
@gregkopp I'm not an ng2 user, so I'm not sure what your code is doing, e.g. do things like `this.actions.loadSucceeded(response)` call dispatch themselves? If yes, this is mostly fighting redux-observable and I would personally consider it an anti-pattern inside epics.

Unless you're creating a custom Observable (most never will need to), you should almost _never_ call `subscribe()` inside your epics. There's no "rules" per say, but it's usually suggestive of anti-patterns.

Instead, more idiomatic would be something _like_ this:

```js
loadData = (action$: ActionsObservable<any>): any => {
  return action$.ofType(ElephantActions.LOAD_DATA)
    .mergeMap((action: any): Action =>
      this.load()
        .map(response => loadSucceeded(response))
        .catch(err => Observable.of(loadFailed(err)))
    );
}
```

That said, if you REALLY want to do what you're doing, slightly more appropriate would be to use `do()` instead of map, then add `ignoreElements()` to the end to basically just throw away everything (the epic stream will no longer output anything at all)

```js
loadData = (action$: ActionsObservable<any>): any => {
  return action$.ofType(ElephantActions.LOAD_DATA)
    .do((action: any): Action => {
      this.load()
        .subscribe((response: any) => {
          this.actions.loadSucceeded(response);
        }, (err: any) => {
          this.actions.loadFailed(err);
        });
    })
    .ignoreElements();
}
```

Using RxJS (and redux-observable) this way isn't evil, but it's really fighting against idiomatic patterns.

***

> According to the documentation, all Epics must return an action.

The docs present this as an absolute (even though it's not) because I've found if I explained that it's possible to _not_ emit actions people focus on that possibility too much and end up doing lots of things imperatively, not embracing idiomatic RxJS. So it's really one of those things to protect newcomers and nudge them in the right direction. If you find yourself with epics that don't emit anything, it's almost always an anti-pattern--a logging epic is one example where it's OK.

**Comment by Axure** [comment]
Probably what you what is `ignoreElements`?
