### ISSUE TITLE
Get change from epic

### ISSUE THREAD

**Issue by belafarinrod91** [redux-observable/redux-observable#196]
Hi @jayphelps ! 

Thanks for this great framework !!! I am really looking forward to use it in my new project. 

While testing, I just came up with a question (which could be really obvious to answer for you): 

When I trigger an asynchronous action from my component, is there any chance to get an event, when the task is done ? How would I know when the api call, for instance, is done in my component ? 

Here are my thoughts (and I don't even know if they are correct or not): I call a webservice with the following command:
`this.myCustomActions.fetchUserDataWithId(2)`

This is already triggering an epic, which is writing the result into my store. I am also able to subscribe the view with the async pipe on the properties, which are returned by the webservice to show them within a view. 

What would I do when I want to use some data from the result, to trigger another webservice or another action ? Would I subscribe on the store to get notified whenever the property was returned by the webservice ? Isn' there a better way to handle that ? 

Thanks !

**Comment by jayphelps** [comment]
Hey please, try to keep future questions on [StackOverflow](https://stackoverflow.com/questions/tagged/redux-observable) or [Gitter](https://gitter.im/redux-observable/redux-observable). We reserve Issues tickets for bugs/RFCs

> What would I do when I want to use some data from the result, to trigger another webservice or another action ? Would I subscribe on the store to get notified whenever the property was returned by the webservice ? Isn' there a better way to handle that ?

When using idiomatic redux-observable, your component wouldn't need to know the sequence because that's business logic. Instead, it would dispatch a single action which delegates everything to your epics. One example would be a single epic which listens for action `A`, then it kicks off `B` and starts listening for `B_FULFILLED`, when received it then kicks off `C`. You'd then have two additional epics, one that handles `B` and one that handles `C`.

**Comment by belafarinrod91** [comment]
@jayphelps, thanks for the clarification !

**Comment by jayphelps** [comment]
@belafarinrod91 you're welcome!
