### ISSUE TITLE
Compatibility with rxJs 5.4.0

### ISSUE THREAD

**Issue by actra-gschuster** [redux-observable/redux-observable#246]
**Do you want to request a *feature* or report a *bug*?**  
[x] A bug

**What is the current behavior?**
Just upgraded to rxJs 5.4.0 (from 5.3.1), now my angular 4.1.1 app stopped working, when compiling it complains that .mapTo() is not available on ActionsObservable.
Downgrading to 5.3.1 solves the issue without any changes in the code.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

```
import { Injectable } from '@angular/core';
import { Action } from 'redux';
import { ActionsObservable } from 'redux-observable';
import { Epic } from 'redux-observable-decorator';
import 'rxjs/add/operator/mapTo';


@Injectable()
export class ClearStateAfterLogoutEpic {
    @Epic() public clearStateAfterLogout: any = (action$: ActionsObservable<any>) => action$
        .ofType('logoutEnded')
        .mapTo(<Action>{type: 'reset-initial/RESET'})
}
```

**What is the expected behavior?**
Should still compile without problems.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
angular 4.1.1
TypeScript 2.3.2
WebPack 2.5.1
redux 3.6.0
redux-observable 0.14.1
redux-observable-decorator 1.1.0
rxJs 5.4.0 failing, 5.3.1 working as expected

**Comment by jayphelps** [comment]
My initial guess is that you somehow have two versions of rxjs installed when this issue is happening, so when you add `mapTo` it actually adds it to a different `Observable` than the one `redux-observable` is importing and extending as `ActionsObservable`.

In that file, can you do this:

```js
// ... existing imports
import { Observable } from 'rxjs/Observable';

@Injectable()
export class ClearStateAfterLogoutEpic {
    @Epic() public clearStateAfterLogout: any = (action$: ActionsObservable<any>) => {
        // confirm it extends the same Observable
        console.log(action$ instanceof Observable);

        // confirm it has mapTo before we chain ofType
        console.log(typeof action$.mapTo === 'function');

        return action$
            .ofType('logoutEnded')
            .mapTo(<Action>{type: 'reset-initial/RESET'})
    }
}
```

Also, search your node_modules and confirm there is only one `rxjs` directory.

![image](https://cloud.githubusercontent.com/assets/762949/25919035/466e0258-3582-11e7-99ba-29f614f41567.png)

***

I looked at the commit differences between 5.3.1 and 5.4.0 and there wasn't anything I see that could cause this--but you should look as well.

**Comment by jayphelps** [comment]
Still having the issue?

**Comment by actra-gschuster** [comment]
Sorry for not responding earlier.
I think it's as you suspected first - maybe angular uses an other version.
I downgraded to 5.3.1 to solve the issue temporarily and wait till all used libs upgrade as well.
