### ISSUE TITLE
Rx.Observable.ajax is not a function

### ISSUE THREAD

**Issue by vincentaudebert** [redux-observable/redux-observable#29]
Hi guys,

I follow exactly the basic example and when I try to have `.ajax()` instead of .`of()`
I get this error:
`Uncaught TypeError: Rx.Observable.ajax is not a function`

Any idea? It looks like RxJS made few changes (https://github.com/ReactiveX/rxjs/issues/1506) impacting `ajax()` but whatever I try, I can't manage to have redux-observable working.

I tried to install rx-dom package and use Rx.DOM.ajax() instead but redux-observable says it doesn't return an Observable object. I'm confused.

**Comment by jayphelps** [comment]
@vincentaudebert Couple things:

Unfortunately RxJS v4 and v5 have totally different npm package names. e.g. `rx-dom` is v4 which is not compatible with v5; which causes your `Uncaught TypeError: Rx.Observable.ajax is not a function` error. v5 does not yet have a separate package for the DOM extensions, that's coming later as you saw in https://github.com/ReactiveX/rxjs/issues/1506. For now, they are included in the core library.

The RxJS v5 is distributed in numerous variations to accommodate everyone. I'm going to assume you're using babel and using at least ES2015 syntax and a module bundler like webpack/browserify, otherwise the answer would be different.

If you're using `rxjs` WITHOUT function-bind syntax (this is probably what you're looking for)
```js
import { Observable } from 'rxjs';
import 'rxjs/add/observable/dom/ajax';

Observable.ajax();
```
If you're using `rxjs` WITH function-bind syntax (requires babel syntax transform installed)
```js
import { Observable } from 'rxjs/Observable';
import { ajax } from 'rxjs/observable/dom/ajax';

Observable::ajax();
```

We're working on a bunch of new example apps and docs to showcase different use cases of varying complexity. Here's one that's in-progress but not quite finished so don't take it as "the correct way" just yet, but you might find it helpful: https://github.com/jayphelps/redux-observable/blob/github-search/examples/react/github-search/src/actions/index.js

**Comment by vincentaudebert** [comment]
Thanks a lot @jayphelps it works with your version.
I don't really understand why Rx.Observable.ajax() is not working (I was using RxJS 5) though...

**Comment by jayphelps** [comment]
@vincentaudebert you're using `import 'rxjs/add/observable/dom/ajax';` first?

**Comment by jayphelps** [comment]
@vincentaudebert also double check you're using importing from `"rxjs/Observable"` and not from just `"rxjs"` root.

```js
import { Observable } from 'rxjs/Observable';
// NOT
import { Observable } from 'rxjs';
```

**Comment by vincentaudebert** [comment]
I was using `import * as Rx from 'rxjs';` as specified here: https://github.com/redux-observable/redux-observable/blob/master/examples/basic/src/actions/index.js#L1

This example is a bit misleading if you want to use ajax() and don't have much experience with Rx.

But all good your answer works perfectly. 
```
import { Observable } from 'rxjs';
import 'rxjs/add/observable/dom/ajax';
```

**Comment by vincentaudebert** [comment]
@jayphelps actually `import { Observable } from 'rxjs/Observable';` doesn't work for me. (just in case someone reads this issue)

I get this error `Uncaught TypeError: _Observable.Observable.ajax(...).map is not a function`

**Comment by jayphelps** [comment]
😕 weird. totes works for me. double check your import paths are all the correct ones.

https://github.com/jayphelps/redux-observable/blob/github-search/examples/react/github-search/src/actions/index.js#L1-L9
![image](https://cloud.githubusercontent.com/assets/762949/15384057/82a53b96-1d4c-11e6-8234

**Comment by vincentaudebert** [comment]
@jayphelps My mistake. I totally misread the error. It's linked to `.map()` not `.ajax()`
Works well too when I include the operator map.

Thanks again for your help :)
