### ISSUE TITLE
OSS funding/sponsors/ads/etc

### ISSUE THREAD

**Issue by jayphelps** [redux-observable/redux-observable#319]
I'm curious if anyone has thoughts, opinions, objections to the various types of funding available for OSS?

[Open Collective](https://opencollective.com) is donation based, seems to have worked well for Webpack, but they're _massive_. Would it be worth it at all for us? [CodeSponsor](https://codesponsor.io) is brand new, basically tailored ads. I'm giving it a try on some of my other projects.

When it comes to projects like redux-observable, I'm not sure if anything is feasible. Even if we could somehow find funding it's not clear how we would divide it up? Some sort of bounty program or hourly rate with the honor system? Who is eligible to collect? Will this all create arguments between us, as money often does?

To be totally clear, I'm not saying "we need funding or I stop maintaining this". Just admitting the amount of OSS I do decreases as time goes by, and it's heavily influenced by feelings of being drained--particularly support related stuff, because it's sometimes frustrating work. This is also pretty common, and a hot topic right now.

Definitely interested in frank, honest opinions. Even if you have objections. 🙏

**Comment by rgbkrk** [comment]
I have no objections to those funding options. I'm happy to lend perspectives though.

nteract's fiscal sponsor is NumFocus, funding comes from other sponsors (largely through grants and early on some corporate sponsorship by paying developers and designers directly). People had different reactions to getting paid, mostly depending on what their association was before.

Some volunteers that did it for fun then switched to getting paid felt constrained, even though it was pretty much the same work. Other volunteers took it in stride as it helped them allocate time to something they loved to work on in a focused deliverables manner.

I've oscillated between both of these. At the end of the day, my most limiting factor is wanting to spend time with family. Getting paid to work on open source (or generally contracting) has offset this for me, easing tension between my partner and I. I've vested a lot of time into Jupyter that has not had immediate material benefit solely because I believe in the project, enjoy working on it, and 

I wish that I could spend more time on redux-observable (and RxJS) myself. While we're using it on nteract, it just works™ and there's nothing else to solve right now relative to our other priorities. The primary way I'd get suckered into engaging more is if we ran a docs sprint (could host it at Netflix). Could even do a Stack Overflow marathon/competition.

It's totally ok to take more steps back Jay and lessen the risk of total burn out. The project will keep getting used, things can go idle for a bit. You are way more important than the project itself. Please reach out to me anytime.

**Comment by jayphelps** [comment]
I've set up a Patreon for donations ❤️ 

https://redux-observable.js.org/BACKERS.html
