### ISSUE TITLE
Sequencing actions together

### ISSUE THREAD

**Issue by nathanvale** [redux-observable/redux-observable#33]
This is a fantastic library. Thank you for sharing!

Would it possible to provide an example that composes two asynchronous  actions together into one asynchronous action that is cancelable?

I believe it is possible however struggling at the movement to get my head around it.

**Comment by jayphelps** [comment]
Would need clarification on what two async actions mean to you, whether they depend on each other, whether they should run concurrently or consecutively, etc.

Here's one example: 

```js
const fetchFirst = () =>
  (action, store) =>
    Observable.ajax('/first');

const fetchSecond = () =>
  (action, store) =>
    Observable.ajax('/second');

const fetchBoth = () =>
  (action, store) =>
    Observable.merge(
      fetchFirst()(action, store),
      fetchSecond()(action, store),
    )
      .takeUntil(actions.ofType(CANCEL_BOTH));
```

**Comment by nathanvale** [comment]
Thanks heaps! That was very helpful.

I have a functional programming background so the core concepts make sense however I am just getting up to speed with RXJS

So your example with merge is for events that happen at any time.

With obserable compilation how would you handle events that should happen in a sequence or depend on each other. I'm aware of zip and combineLatest however still a little unclear.

**Comment by istarkov** [comment]
As in rx it is no a one way, 
for sequence you could use `concat` + `defer`

```javascript    
  Observable.concat(
      Observable.defer(() => fetchFirst()(a, s)), // first defer just for example
      Observable.defer(() => fetchSecond()(a, s))
    )
```

for dependent you could use something like
```javascript
fetchFirst()(a, s).flatMap(() => fetchSecond()(a, s))
```

**Comment by jayphelps** [comment]
@nathanvale In sequence would be the static [`concat`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-concat), if they depend on each other you could just use the [`mergeMap`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-mergeMap) (alias: `flatMap`) operator on the first stream.

http://jsbin.com/niyawo/edit?js,console
```js
Observable.of(1, 2, 3)
  .flatMap(value => Observable.of(value + 1))
  .subscribe(value => console.log(value));
// 2..3..4
```

**Comment by jayphelps** [comment]
Closing since it sounds like these are mostly RxJS questions.

**Comment by jayphelps** [comment]
@istarkov you only need `defer` if your observable is hot, which isn't the case for `ajax` and most.

http://jsbin.com/niyawo/edit?js,console,output

```js
Observable.concat(
  Observable.ajax('https://api.github.com/search/repositories?q=first'),
  Observable.ajax('https://api.github.com/search/repositories?q=second'),
)
  .subscribe(value => console.log(value));
// the second ajax call won't start until the first completes.
```

**Comment by istarkov** [comment]
As I understand In your case both requests will be run in parallel and just result will be combined in a sequence, In my case requests will be run one after other.

**Comment by jayphelps** [comment]
@istarkov check out the jsbin demo, that isn't the case. cold observables do not do anything special until they are subscribed to, the second `AjaxObservable` won't be subscribed to until the first completes.

**Comment by istarkov** [comment]
O sorry, I never used ajax and used `Observable.fromPromise` and in that case
```
    Observable.concat(
      Observable.fromPromise(fetch(a)),
      Observable.fromPromise(fetch(b))
    )
```

is not the same as 
```
    Observable.concat(
      Observable.defer(() => Observable.fromPromise(sleep())),
      Observable.defer(() => Observable.fromPromise(sleep()))
    )
```
Thank you

**Comment by jayphelps** [comment]
@istarkov right on. Yeah, Promises by their nature are hot, so wrapping them in an Observable can't make them cold. You're totally right that using `defer` in that cause is what you'd want to do. `Observable.ajax` supports cancellation, so it's a good idea to use it if you can over Promise-based APIs like `window.fetch()` which can't be.

Cheers! :shipit:

**Comment by nathanvale** [comment]
This thread has explained everything. Using this middleware instead of thunk middleware is going to make app development even more fun.

Cheers!

**Comment by cmelion** [comment]
Prior to Epics we could sequence operations using concat:
```
export const createItem = (item) => (
    () => Observable.ajax.post(BASE_URL, JSON.stringify(item), HEADER)
    // When our request comes back, we transform it into an action
    // which the redux-observable middleware will then dispatch
        .map(
            payload => ({
                type: CREATE_ITEM,
                payload: Array.isArray(payload.response) ? payload.response[0] : payload.response
            })
        )
        .catch(error => Observable.of({type: ITEM_ERROR, payload: error}))
);

export const selectItem = (item) => (
    () => Observable.of({type: SELECT_ITEM, payload: item})
);

export const createAndSelectItem = (item, itemToSelect) => (
    (actions) => (
        Observable.concat(
            createItem(item)(),
            selectItem(itemToSelect)()
        ).takeUntil(actions.ofType(ITEM_ERROR))
    )
);
```

I'm having trouble adapting this to the epic workflow, has anyone tried this.

**Comment by jayphelps** [comment]
@cmelion We're still fleshing out our official suggestions around this, but here's what I'd recommend at the moment.

The general idea is to use epic composition. You'll want to "spawn" a new instance of the epic you want to wait for. Epics are intentionally factory functions for this reason.

So let's say the epic that listens to create items:

```js
const createItemEpic = action$ =>
  action$.ofType(CREATE_ITEM)
    .mergeMap(action =>
      Observable.ajax.post(URL, action.payload)
        .map(createItemFulfilled)
        .catch(error => Observable.of(
          createItemRejected(error)
        ))
    );
```

You can create an instance of your epic just by calling it with the expected arguments:

```js
const actions$ = /* ??? */;

createItemEpic(actions$);
```

You can create your own `ActionsObservable`, but the process isn't as elegant as we'd like due to some [existing RxJS limitations](https://github.com/ReactiveX/rxjs/issues/1876) we're working on fixing.

But you can write a helper to create a new instance of your epic and run it against a precanned list of actions like this:

```js
const spawnEpic = (epicFactory, ...actions) => {
  const input$ = Observable.of(...actions);
  const actions$ = new ActionsObservable(input$);
  return epicFactory(actions$);
};

const output$ = spawnEpic(createItemEpic, { type: CREATE_ITEM });
```

So why did I explain all of that? Because you're looking for explicit control over the lifecycle of `createItemEpic`. Using this "spawning" inside a parent epic you can pipe its output and respond to its lifecycle like wait for a particular action it will emit or more simply just wait until it completes. Because we've providing a custom `action$` (ActionsObservable), the spawned epic will `complete()` after it exhausts the actions we gave it.

All that put together looks like this:

```js
const createAndSelectItemEpic = action$ =>
  action$.ofType(CREATE_AND_SELECT_ITEM)
    .mergeMap(action =>
      spawnEpic(createItemEpic, createItem(action.payload.item))
        .concat([
          selectItem(action.payload.selectItem)
        ]),
    );

// other boilerplate for reference
const createItem = payload => ({
  type: CREATE_ITEM,
  payload
});
const createItemFulfilled = payload => ({
  type: CREATE_ITEM_FULFILLED,
  payload
});
const createItemRejected = payload => ({
  type: CREATE_ITEM_REJECTED,
  payload,
  error: true
});

const selectItem = payload => ({ type: SELECT_ITEM, payload });
```

In your example your `selectItem` thunkservable was emitting a single action synchronously so it did not need to be a thunkservable; I make it just a plain old action in the example above.

HOWEVER, if you really do need to run a particular epic, wait for it to end, then run yet another epic, etc you can use the same pattern:

```js
const createAndSelectItemEpic = action$ =>
  action$.ofType(CREATE_AND_SELECT_ITEM)
    .mergeMap(action =>
      spawnEpic(createItemEpic, createItem(action.payload.item))
        .concat([
          spawnEpic(selectItemEpic, action.payload.selectItem))
        ]),
    );
```

Keep in mind that you can use other RxJS combining strategies like `merge`, `race`, `zip`, etc.

We're absolutely looking at ways we can make this ability more obvious to people, including adding custom ActionsObservable operators and/or helpers for spawning epics.

**Comment by cmelion** [comment]
@jayphelps have there been any changes to the above recommendations?

**Comment by jayphelps** [comment]
Nope. It's still the status quo for me--open to hearing other community patterns of course.

**Comment by MVSICA-FICTA** [comment]
Would this not solve the issue? https://github.com/ReactiveX/rxjs/pull/2529

**Comment by jayphelps** [comment]
@MVSICA-FICTA hmm I don't follow? Seems unrelated.

**Comment by MVSICA-FICTA** [comment]
@jayphelps Sorry bout that, guess I was reading over the issues leading toward the new compose operator for RxJS and got a little enthusiastic but the time I got here 😊 

The new compose functionality to enhance the let operator does look good though. With un/subscribing of observers RxJS has a macro side to building modular solutions and with compose it now has the micro side, for sequencing together functions. How wonderful is that!

**Comment by tarr11** [comment]
This issue was the main reason I was considering Redux-Observable instead of using Redux-Thunk.   Based on this thread,  I still don't really understand how to do it effectively.  A simple recipe with this example may be helpful.  I've looked at redux-saga, it seems like they handle this case a lot more fluidly.  I admit I am new to RxJS so that may be the issue.

I've posted
https://stackoverflow.com/questions/44218356/how-to-populate-the-store-and-sequentially-await-return-using-redux-observable

This feels like a common scenario - create an epic that populates the store from ajax, wait for its results, read the store and populate some more of the store in sequence.

**Comment by slothyrulez** [comment]
Hi, and first of all thanks for the library.

I've been reading this issue and, find the forkEpic helper super useful, but can't see how to inject possible dependencies on the epic factory

```
export const forkEpic = (
  epicFactory,
  actions = [],
  dependencies = getDependencies(),
) => {
  const input$ = Observable.of(...actions);
  const actions$ = new ActionsObservable(input$);
  return epicFactory(actions$, ...dependencies);
};
```

That is my best bet, but is not working.

**Comment by jayphelps** [comment]
@slothyrulez if you're using the dependencies feature of createEpicMiddleware then you'll need to pass along those dependencies to your call to `forkEpic` as well.

```js
// obv feel free to change signature to your preference
// e.g. (epicFactory, actions, dependencies)
const forkEpic = (epicFactory, dependencies, ...actions) => {
  const input$ = Observable.of(...actions);
  const actions$ = new ActionsObservable(input$);
  return epicFactory(actions$);
};

const createAndSelectItemEpic = (action$, store, dependencies) =>
  action$.ofType(CREATE_AND_SELECT_ITEM)
    .mergeMap(action =>
      forkEpic(createItemEpic, dependencies, createItem(action.payload.item))
        .concat(
          forkEpic(selectItemEpic, selectItem(action.payload.selectItem)) // no array literal wrapper!
        ),
    );
```

**Comment by slothyrulez** [comment]
@jayphelps First of all, thanks for your help.

My problem was on one of the epics, doing destructuring on the dependencies param: 

```js
export const videoUploadEpic = (action$, store, { fileUpload }) =>  {
  action$.ofType(UPLOAD_VIDEO).mergeMap(action =>
    fileUpload(action.payload)
      .mergeMap(response =>
    ...
}
```

Surprisingly, that was causing the 'fileUpload' dependency being `undefined`.

Changed it to:

```js
export const videoUploadEpic = (action$, store, dependencies) =>  {
  const { fileUpload } = dependencies;
  action$.ofType(UPLOAD_VIDEO).mergeMap(action =>
    fileUpload(action.payload)
      .mergeMap(response =>
    ...
```
Now is working like a charm!!!


The final version of the forkEpic helper:
```js
export const forkEpic = (epicFactory, store, dependencies, ...actions) => {
  const input$ = Observable.of(...actions);
  const actions$ = new ActionsObservable(input$);
  return epicFactory(actions$, store, dependencies);
};
```

And the epic using `forkEpic`:

```js
export const profileImageUpdateEpic = (action$, store, dependencies) =>
  action$
    .ofType(PROFILE_IMAGE_UPDATE)
    .mergeMap(action => {
      const { id } = action.payload;
      return forkEpic(imageUploadEpic, store, dependencies, uploadImageAction(action.payload))
        .concatMap(epicResult => {
          const { imageUrl } = epicResult.payload;
          return forkEpic(profileUpdateEpic, store, dependencies, requestProfileUpdate({ id, imageUrl }));
        })
    })
```

Again, many thanks for your time, I don't have much experience with rx, ans sometimes mix concepts.
And as a note, being able to do this stuff with the epics is nice, since it makes epics reusable.

**Comment by jayphelps** [comment]
```js
export const videoUploadEpic = (action$, store, { fileUpload }) =>  {

// vs.

export const videoUploadEpic = (action$, store, dependencies) =>  {
  const { fileUpload } = dependencies;
```

hmm that destructuring thing should not be an issue. Triple check you didn't maybe misspell `fileUpload` or you can prolly figure out what's causing it by pausing the debugger when it's called. If all of that checks out, might be a compiler bug (but relatively rare). Are you using Babel or TypeScript?

**Comment by slothyrulez** [comment]
@jayphelps 

This is a react-native app, I think it uses webpack and babel under the hood.

Without destructuring
```js
var imageUploadEpic = exports.imageUploadEpic = function imageUploadEpic(action$, store, _ref) {
  var fileUpload = _ref.fileUpload;
```
Destructuring
```js
var imageUploadEpic = exports.imageUploadEpic = function imageUploadEpic(action$, store, dependencies) {
  var fileUpload = dependencies.fileUpload;
```

**Comment by jayphelps** [comment]
@slothyrulez yep those are semantically identical--what you name a variable makes no difference as long as it's used the same. Most likely the issue was elsewhere and that was a red herring. If you're still looking to figure it out, pausing your debugger in there should give you enough insight to figure out why it's happening. E.g. is `_ref_` really undefined? If so, why? (look up the callstack, etc)

**Comment by stevematdavies** [comment]
The lack of clear and simple examples for this is astounding. I have the same issue, except I wish to pass the results of one request into the next. A very common practice indeed, one which seems to be well supported in theory by redux-observable, 

```
const loginEpic = actions => {
    const loginRequest = credentials =>  Observable.ajax(POSTOptions('/api/login', credentials));
    const providerRequest = (userToken, serviceProviderId) => Observable.ajax(GETOptions('/api/provider', [userToken, serviceProviderId]));
    return actions.ofType(ActionTypes.LOGIN_REQUESTED)
        .mergeMap(({credentials}) =>   
            loginRequest(credentials)
                .map(r => loginResolvedAction(r.response))
                .catch(err => Observable.of(loginFailedAction(err.response.message))));                
}
```

Where could I put in my `providerRequest `using the response of the loginRequest as a parameter, and then return all in the `loginResolvedAction`?

I have been swimming in the much of stack exchange, and I cannot find one clear relevant answer, I have asked questions and been ridiculed for it or pointed to incorrect answers. Any help her would be appreciated!

It's so frustratingly bad, to find direction. even from official docs on RXJS, that I was wondering if it would be better to go back to good old chained promises, and give up epics?

**Comment by Tomekmularczyk** [comment]
Hi, I have a problem that I don't know how to resolve. I've posted it also on [stackoverflow](https://stackoverflow.com/questions/48261438/rxjs-and-redux-observable-combining-actions-into-one). Maybe someone could point me to solution.

I have two epics that do requests to api and update the store:

```javascript
const createPaymentMethod = (action$: any, store: any) =>
  action$.ofType(CREATE_PAYMENT_METHOD)
    .mergeMap(action =>
      ajax(api.fetchProjectScenes(action.payload.projectId), store)
        .map((response: Object) => ({
          type: CREATE_PAYMENT_METHOD + SUCCESS,
          payload: {
            data: response.response,
            status: response.status,
          },
        }))
        .catch((error: Object) =>
          Observable.of({
            type: CREATE_PAYMENT_METHOD + FAILURE,
            error: {
              response: {
                data: error.xhr.response,
                status: error.xhr.status,
              },
            },
          }),
        ),
    );

const changeTeamSubscriptionPlan = (action$: any, store: any) =>
  action$.ofType(CHANGE_TEAM_SUBSCRIPTION_PLAN)
    .mergeMap(({ payload }) =>
      ajax(api.deleteScene(payload.projectId, payload.sceneId), store)
        .map((response: Object) => ({
          type: CHANGE_TEAM_SUBSCRIPTION_PLAN + SUCCESS,
          payload: {
            data: response.response,
            status: response.status,
          },
        }))
        .catch((error: Object) =>
          Observable.of({
            type: CHANGE_TEAM_SUBSCRIPTION_PLAN + FAILURE,
            error: {
              response: {
                data: error.xhr.response,
                status: error.xhr.status,
              },
            },
          }),
        ),
    );
```

Now I have a simple scenario where I would like to create the third action that combines the two above, let's call it `createPaymentMethodAndChangeTeamSubscription`. How can I do it?
I think in many cases (and in my) it's important that result of the first action is dispatched to the store before the second begins. That would be probably trivial to do with Promises, but I can't somehow think of a way to do it with `rxjs` and `redux-observable`.

Thanks in advance!

**Comment by cmelion** [comment]
@Tomekmularczyk I use concat when I need one action(or epic via forkepic) to start after another successfully completes.   The createAndSelectItemEpic discussed above is applicable but since ajax is not involved it may not be obvious.  A closer example might be something like following jsbin where the results of an ajax call are used to perform a dependent animation:

http://jsbin.com/vegonak/embed?js,output

**Comment by Tomekmularczyk** [comment]
@cmelion Correct me if I'm wrong but I think that's a bit different scenario because it would require changing one of the epics above (use `concat` on the first one to fire the second one), while I want them to do only what they are doing now (so I can call them separately in different occasions). What I want is another action that will **compose** these two together. In other words:

Sometimes I just want to create payment method and do nothing else. Other times I just want to change team subscription and do nothing else...
```javascript
const createPaymentMethod = (action$, store) =>
  action$.ofType(CREATE_PAYMENT_METHOD)
  // ....

const changeTeamSubscription = (action$, store) =>
  action$.ofType(CHANGE_TEAM_SUBSCRIPTION_PLAN)
 // ....
```

... but there are situations where I want to do both, one after another:
```javascript
const createPaymentMethodAndchangeTeamSubscription = (action$, store) =>
 // fire CREATE_PAYMENT_METHOD
 // ... wait untill it finished ...
 // ... now fire CHANGE_TEAM_SUBSCRIPTION_PLAN
```

**Comment by cmelion** [comment]
@Tomekmularczyk 

I'd have to dig up the working code, it's been almost a year since I've touched this stuff, but you use something like forkEpic within a concat statement to achieve exactly what you described.

```
// obv feel free to change signature to your preference
// e.g. (epicFactory, actions, dependencies)
const forkEpic = (epicFactory, dependencies, ...actions) => {
  const input$ = Observable.of(...actions);
  const actions$ = new ActionsObservable(input$);
  return epicFactory(actions$);
};

const createAndSelectItemEpic = (action$, store, dependencies) =>
  action$.ofType(CREATE_AND_SELECT_ITEM)
    .mergeMap(action =>
      forkEpic(createItemEpic, dependencies, createItem(action.payload.item))
        .concat(
          forkEpic(selectItemEpic, selectItem(action.payload.selectItem)) // no array literal wrapper!
        ),
    );
```

**Comment by Tomekmularczyk** [comment]
@cmelion alright I'll look into it. Thanks!

**Comment by Tomekmularczyk** [comment]
@cmelion I actually managed to do this with the way you and @jayphelps explained in this topic. I posted an answer on [stack overflow](https://stackoverflow.com/questions/48261438/rxjs-and-redux-observable-combining-actions-into-one/48307271#48307271) if you were interested. Thanks!

**Comment by cmelion** [comment]
@Tomekmularczyk Cool, totally agree about inclusion hope @jayphelps does too!

**Comment by shenlin192** [comment]
Hello @jayphelps, your `forkEpic` approach is great. But what should I do if I want the `createItem` action **really go through reducers to change states in the store**? 

For example, I need to set an attribute `pending` to `true` when `createItem` is dispatched and then set  `pending` to `false` when `createItemFulfilled` is dispatched. At the same time, I would like to reuse  `createItemEpic` and `selectItemEpic` as you do.

**Comment by abdurahmanus** [comment]
@shenlin192  I've faced the same problem. Did you find the solution?

**Comment by rachelgshaffer** [comment]
I searched SO a bunch but can't seem to find any examples for the new v6 syntax. @jayphelps would you mind posting a solution?

**Comment by jMalojlo** [comment]
@abdurahmanus @shenlin192 
I’m a bit late to the party, but I struggled with the same thing and managed to solve it with a different pattern.  It allows your epics to still do just one thing and your actions to go through the reducers.
 I wrote a blog post about it: https://medium.com/@jmalojlo/sequencing-asynchronous-actions-with-redux-observable-1d050f30d2fb

**Comment by alekpentchev** [comment]
> I searched SO a bunch but can't seem to find any examples for the new v6 syntax. @jayphelps would you mind posting a solution?

I would love some additional explanation for the new syntax. 
I'm struggling right now with chaining several epics one after another only if the previous has completed without an error. Above examples don't work (I used mainly the long one from @jayphelps ) and I see "Object()() is not a function" with a stacktrace to ActionsObservable.
