### ISSUE TITLE
Troubleshooting docs: epics fail silently when returning subscribe from epic

### ISSUE THREAD

**Issue by hendrikswan** [redux-observable/redux-observable#331]
When you return a subscribe from an epic, it just fails silently and none of the epics execute. I'm going to submit a PR with an example on how to do side effects without using `subscribe`.

**Comment by jayphelps** [comment]
This is unfortunately another example of #263 and https://github.com/ReactiveX/rxjs/issues/2813. There is an error about not providing an Observable where it was expected, it's just being swallowed silently due to a bug.

As https://github.com/ReactiveX/rxjs/issues/2813 mentions though, while this is a bug, in the future this behavior will likely be intentional, though almost certainly with a better debugging experience by still showing the error in the debug console (which is what most people actually care about when they freak out about this change lol).
