### ISSUE TITLE
switchMap doesn't exist on type ActionsObservable

### ISSUE THREAD

**Issue by selfrefactor** [redux-observable/redux-observable#371]
**Do you want to request a *feature* or report a *bug*?**  

I hope it is a bug.

**What is the current behavior?**

```
import { ActionsObservable } from 'redux-observable'

export const rootEpic = (action$:ActionsObservable<{type:'GET_ALL_PRODUCT'}>) => {
  
  return action$.ofType('GET_ALL_PRODUCT').switchMap(...)
  // swithMap is not a recognized method
}
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

**What is the expected behavior?**

Typescript should recognize switchMap, instead it shows set of methods which don't include any of `switchMap, map, filter` methods.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

Version 0.17.0
I try it also no 0.16 and 0.15 to no success.

**Comment by jayphelps** [comment]
Hey there. 👋 Definitely not a bug.

I’m happy to help if you throw the question up on StackOverflow—but you’ll need to include a lot more information on how to reproduce. Tag it with “redux-observable”

I’ve seen variations of this before many times. Generally speaking your issue sounds like you either haven’t importing those operators (or all of rxjs) or that you have more than one version of rxjs accidentally installed. Eg v4 and v5, or multiple v5 copies.

See you on StackOverflow.

**Comment by selfrefactor** [comment]
Thanks for quick reply on Saturday.
I was just coming to close the issue myself.

I needed this line and it works:
`import 'rxjs/add/operator/switchMap';`

**Comment by jayphelps** [comment]
Woot! So glad you got it fixed. Enjoy your weekend.

**Comment by brunolm** [comment]
I do have

```
import 'rxjs/add/operator/mergeMap';
```

and

```
(action$: ActionsObservable<{ type: 'getApiValue' }>, store) => {
      return action$.ofType('getApiValue')
```

But I can't see anything other than `ofType` and `lift`

![image](https://user-images.githubusercontent.com/706078/41415118-225779ae-6fbe-11e8-88f6-a2a26ddfcb0c.png)

**Comment by brunolm** [comment]
![image](https://user-images.githubusercontent.com/706078/41416085-7da2c488-6fc0-11e8-8e77-75995502aaba.png)

```
    "redux-observable": "^0.19.0",
    "rxjs": "^6.2.1",
```

**Comment by jayphelps** [comment]
@brunolm Hey 👋  your issue is most likely that you're using rxjs v6 with redux-observable 0.19.0 which requires rxjs v5. So what is happening is that two versions of rxjs are being installed and the Observable redux-observable gives you is not the same Observable you're adding the operators to.

You'll need to either backdown your rxjs version to v5 or upgrade redux-observable to one of the 1.0.0 pre-releases which support rxjs v6. right now the latest is 1.0.0-beta.1 and there's a [migration guide here](https://redux-observable.js.org/MIGRATION.html)

**Comment by jayphelps** [comment]
Alternatively since it appears you're using rxjs-compat you may be able to force redux-observable 0.19.0 to use v6 of redux-observable (utilizing the rxjs-compat layer) by overriding the resolver in your bundler. If you're using webpack, it should be something _like_ this, but untested:

```js
resolve: {
    alias: {
        'rxjs': require.resolve('rxjs')
    }
}
```

Why this works is because webpack aliases override any sub-dependency version requirements of your direct dependencies (and yours as well, but `require.resolve('rxjs')` will prefer _your_ dependency version of rxjs).

Let me know if this works for you, I'm interested to know as I could add this to the documentation.
