### ISSUE TITLE
Websocket integration error

### ISSUE THREAD

**Issue by fingermark** [redux-observable/redux-observable#42]
I'm trying to integrate with a websocket, but get the following error and don't know why:  ```Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.```

Any ideas?  Redux Observable seems to be working for everything else just fine.

```
export function startWebsocket() {
  return (actions, store) => Observable
    .webSocket({
      url: 'wss://example.com/ws/data',
      resultSelector: (msgEvent) => msgEvent.data
    })
    .map((payload) => ({ type: WEBSOCKET_DATA, payload }))
    .takeUntil(actions.ofType(STOP_WEBSOCKET))
    .catch((err) => {
      console.log('ws error', err);

      return Observable.of({type: 'DUMMY'});
    });
```

**Comment by fingermark** [comment]
It's like the map isn't applying.  If I add a log middleware it says it's dispatching on the raw data that's coming in from the websocket.

**Comment by fingermark** [comment]
What I don't understand is why it works outside of redux-observable:  http://jsbin.com/kutituhixe/edit?js,console

I spent an hour trying to create an online demo of it not working, but couldn't due to no UMD package and all of the non-jsbin.com solutions being really terrible to work with.

**Comment by fingermark** [comment]
Full demo of it not working:  https://gist.github.com/fingermark/da59bd63d8663c777edf49a9c68efea8

**Comment by fingermark** [comment]
Works just fine with a custom websocket implementation.  Really confused:

```
function createWebSocket(url) {
  let ws = new WebSocket(url);

  let observable = Observable.create(
    (obs) => {
      ws.onmessage = obs.next.bind(obs);
      ws.onerror = obs.error.bind(obs);
      ws.onclose = obs.complete.bind(obs);
      return ws.close.bind(ws);
    }
  );

  let observer = {
    next: (data) => {
      if (ws.readyState === WebSocket.OPEN) {
        ws.send(JSON.stringify(data));
      }
    },
  };

  return Subject.create(observer, observable);
}
```

**Comment by jayphelps** [comment]
@fingermark testing things briefly, it appears that the bug happens when you add *any* operator after the first `map`.

Seems to be an RxJS v5 bug, most likely with `WebSocketSubject`.

Your jsbin didn't have the issue because you only did `map`. Here's an example reproducing by just adding one more map that is effectively a noop but induces the bug: http://jsbin.com/kidawe/edit?js,console

If you agree, I would head over to [ReactiveX/rxjs](https://github.com/ReactiveX/rxjs) and report the bug there, since it's not related to redux-observable and reproducable with just plain old Rx.

**Comment by jayphelps** [comment]
Thanks for giving a great reproduction demo btw. Very helpful!

**Comment by fingermark** [comment]
@jayphelps thanks so much.  I was going crazy.
