### ISSUE TITLE
Testing observables with fromPromises

### ISSUE THREAD

**Issue by FreddieOD** [redux-observable/redux-observable#492]
Hello and thank you all for your good work.

SO question is essentially [here](https://stackoverflow.com/questions/44122471/rx-observable-frompromise-not-working-with-redux-observable-epics/50236283#50236283). I have given a solution on that SO question that worked for me but I can't help but think that the manipulation of the js event loop and [microtask](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/) scheduling is not the right way to go. 

Test Scheduler, at a glance, does not seem like a reliable solution - from the docs "If the code consumes a Promise or does scheduling with AsapScheduler/AnimationFrameScheduler/etc it cannot be reliably tested with TestScheduler, but instead should be tested more traditionally" - what is meant by "more traditionally".

I have searched far and yonder for a suitable solution. See [here](https://github.com/redux-observable/redux-observable/issues/144) and [here](https://stackoverflow.com/questions/43188196/redux-observable-failed-jest-test-for-epic/43188527). I tried to implement various other solutions but mine seems to be the only one I can get to work.

Maybe the given solution is useful for others with a similar problem, but is there a better way of testing an epic that waits on the resolution of a promise?

```
export const frontPageEpic = (action$, store, api) =>{
  return action$.ofType(TypeKeys.CHANGE_NAME)
    .mergeMap(action => {
      return fromPromise(api.getRequest("http://someHost:8080"))
      .map (result => {
        return { type: TypeKeys.NAME_CHANGED, payload: {changed: true, result: result}}
      })
      .catch(error => {
        ...
      })
    })
}
```
With jest test:
```
describe('fetchUserEpic', () => {
...
  it('produces the user model', () => {
    store.dispatch({
        type: TypeKeys.CHANGE_NAME,
        payload: {name: "bob"}
    });

    // setTimeout places function on the stack to get consumed by the event loop after all microtasks such as promises
    setTimeout(() => {
      expect(store.getActions()).toEqual([
          { type: TypeKeys.CHANGE_NAME, payload: {name: "bob"} },
          { type: TypeKeys.NAME_CHANGED, payload:{changed: true} }
      ]);
    }, 0)

  });
});
```
Without that setTimeout my test fails because the promise doesnt get resolved before the main test script finishes.

**Comment by jayphelps** [comment]
Hey @FreddieOD 

> what is meant by "more traditionally".

The [Known Issues](https://github.com/ReactiveX/rxjs/blob/master/doc/marble-testing.md#known-issues) section includes an example of what it means. It just means how you would test Promise code or how you would test RxJS code if TestScheduler wasn't a thing. i.e. you use your testing frameworks features for testing async code, like a `done()` callbacks.

![image](https://user-images.githubusercontent.com/762949/39785694-13d4ebae-52eb-11e8-8435-b514a65d3a23.png)

***

While there's no silver bullet, in your specific case I would extract the Promise logic out of the epic entirely by having `api.getRequest` return an Observable. Then when you mock it out in your epic test, you don't have to deal with it at all. I'm not sure what the source for `api.getRequest` is, so I can't give you an example other than that your `fromPromise` would be moved into it.

If you'd like to also test the helper, you would do so with traditional async testing patterns and mocking or stubbing. [Jest supports the same async patterns](https://facebook.github.io/jest/docs/en/asynchronous.html) that most testing frameworks do: the `done()` callback or returning a Promise from the test.

Btw since you're using Jest you could also use it's import mocking features instead of using redux-observable's dependency injection techniques. I don't yet have a solid opinion on which should be considered "better", just throwing it out there.

**Comment by FreddieOD** [comment]
Makes sense. Will investigate. Thanks.
