### ISSUE TITLE
[PROPOSAL] redux-saga like server side rendering

### ISSUE THREAD

**Issue by hitmands** [redux-observable/redux-observable#502]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**What is the current behavior?**
A running epic cannot be terminated due to `epicMiddleware#run` missing its complementary API `epicMiddleware#terminate`

**What is the expected behavior?**
As a user I expect to run/terminate any epic.

**Which versions of redux-observable?**
`latest`

**Potential Usages**
1. **Server Side Rendering** where you need to perform some operations before serving the html to the browser
2. **Code Splitting** where you need to add/remove epics on-the-fly (redux provides the [`replaceReducer`](https://redux.js.org/recipes/code-splitting#using-replacereducer) API).

In https://github.com/redux-observable/redux-observable/pull/539 I am proposing an actual implementation:

```typescript
interface EpicMiddleware {
  // sends termination signal via the actions stream (can be caught and ignored),
  kill(Epic): Observable,

  // kills the process and cannot be caught.
  sigterm(Epic): Observable,
}
```

### Resources

- https://www.google.com/search?q=difference+between+sigterm+and+sigkill&oq=difference+between+sigter&aqs=chrome.0.0j69i57j0l6.4509j1j7

**Comment by evertbouw** [comment]
This proposal is quite different from https://github.com/redux-observable/redux-observable/pull/412, now I'm not using SSR myself so I don't know what's required for it, but I'd love to get a discussion going!

ping @Jerry-Hong @chiel

**Comment by hitmands** [comment]
Hello, 
I was just wondering if this might be falling into an oblivion...

please, let me know how can I help.
Giuseppe

**Comment by jayphelps** [comment]
I think @BerkeleyTrue has experience with using redux-observable in SSR. Maybe he has thoughts?

**Comment by deanius** [comment]
I think I follow - you want a way to hook the end of all epics triggered by initializing an app, because only then will all its data be ready? And your application of that is for SSR. 

If that's true, I think stating this issue in terms of that might draw out a little more discussion..

I've been thinking about this type of issue for some time - I've been working on solving it outside of RO.. But basically I think you're more or less on the same train as me: 

If you have a list of epics you're waiting on, then the `forkJoin` of them contains the results of all their completions. So when that observable emits, that's your hook. The key is to know which renderers are set into flight by each action (the initialization action included). And for that you may manually track that in a read-only, non-serializable property of the `action.meta`, or in some other place.

I'd be interested to hear if this jives with your approach either.

**Comment by hitmands** [comment]
Ok, I am going to give it a try, I think your suggestion could be the right way to go.
a pr with a basic implementation will follow.

**Comment by hitmands** [comment]
The idea behind this pull request is to implement a `terminate` behaviour, so, after `epicMiddleware.terminate()` has been called no more actions will be sent through the epics and once they've completed the application will be ready to be rendered.

If we can agree with something like that, then I could provide some example.

**Comment by chiel** [comment]
Sorry, I didn't really pay attention to the fact that I was actually pinged here. One potential downside (albeit a small one) I see to this approach is that your epics should be not combined before hand, which the approach I'm currently using (with the closableEpic) does not require. My knowledge of rxjs, and by extension redux-observable, is somewhat limited though, so I'm very open to taking a different approach.

Currently we're just using the code from #412 which works a charm, but of course it would be preferable to have an "official" approach from redux-observable, leaving us with less code to maintain.

**Comment by hitmands** [comment]
Hi @chiel, 
could you also give me some feedback about #539, I think 
> your epics should be not combined before hand
is now sorted out.

**Comment by chiel** [comment]
Implementation-wise I can't really say much about it to be honest, I just don't have the required knowledge. My SSR use case is fairly simple since I just fetch data from the server, I can't really tell if this approach or the one in #412 is better. Sorry I can't be of more help.

**Comment by hitmands** [comment]
I see.
Let's wait for any update about this feature.
