### ISSUE TITLE
Canceling of all async actions?

### ISSUE THREAD

**Issue by matthewwithanm** [redux-observable/redux-observable#51]
is there some way to cancel all asynchronous actions when you want to destroy the store? If not, please consider this a feature request 😊. For example, a special action type that gets used with `takeUntil` at subscription time [here][1].

[1]: https://github.com/redux-observable/redux-observable/blob/5ff584cf191710d690355a76fb7212f18ad97300/src/reduxObservable.js#L16

**Comment by istarkov** [comment]
Having that `dispatch(observableAction)` returns subscription, you can unsubscribe in `componentWillUnmount` like here https://github.com/redux-observable/react-redux-observable/blob/master/src/dispatchOnMount.js#L20
or in any other places.

Also you could `wrap` your actions with takeUntil wrapper like 
https://jsfiddle.net/0b6rd7w0/

Also you could use process Manager for any async work and just use takeUntil there.

**Comment by jayphelps** [comment]
@matthewwithanm while we're haven't yet launched the new documentation on the process manager style, it will likely become the de facto standard replacing thunkservables (the current documented way).

Since redux doesn't have a first-class concept of "destroying the store", can you clarify what you mean?

We're considering adding the ability to stop your root process manager (which all others derive from) which is helpful for server rendering. Most likely this will be done gracefully, in the sense that the `ActionsObservable`, that your process managers receive, will complete which means as soon as any existing streams you created off it it complete (like ajax calls) the entire chain is done and complete.

**Comment by jayphelps** [comment]
Sorry that the docs on process managers aren't done yet. They're basically the same as the thunkservables except they are long-lived. If you're familiar with redux-saga, it's almost the same but with streams.

Here's a demo http://jsbin.com/nizova/1/edit?js,output

```js
```

**Comment by matthewwithanm** [comment]
Thanks @istarkov but I'm looking to not have to do it in n locations.

@jayphelps Yeah, I'm watching #44 (: It actually seems basically the same as [a pattern][0] we're already using in [Nuclide].

Stopping the root process manager is exactly what I'm looking for. For context, packages can be deactivated by the user at any time in Atom, and at that point we'd want to cancel all of the async work being done for a given store (each package would have a store). Ideally, we would be able to do this in one location instead of on every process manager.

[Nuclide]: https://github.com/facebook/nuclide/
[0]: https://github.com/facebook/nuclide/blob/ddd52bfe54fad02e98b19cc2f1492cc66f69eea4/pkg/nuclide-build/lib/applyActionMiddleware.js

**Comment by jayphelps** [comment]
@matthewwithanm in your use case, does a graceful completion (described above) work for you or does it need to be immediate; which would cancel any inflight async side effects like i/o and could leave things in a bad state if you're not careful.

**Comment by matthewwithanm** [comment]
lol I almost mentioned that! My first reaction was that we need something immediate, but I could also understand the perspective that if process managers don't complete when the input stream does, they're buggy. Certainly immediate completion would be less error prone though.

**Comment by jayphelps** [comment]
just to clarify since my phrasing was a little ambiguous: if we "graceful" complete, any async observables won't be abruptly cancelled/completed, instead process managers would just not receive any more actions causing them to complete when anything they were already doing completes.

If we abruptly terminate the entire stream chain, what happens if your process manager was in the middle of a series of async operations? e.g. compile two files concurrently writing to some `tmp` dir then moving them to the final location when both are done. If we suddenly kill that process, you could end up with files out there in la la land that are never cleaned up or worse since your code is run on a desktop, if someone spawns out another actual OS-level process it could be orphaned. 

If this was shutdown gracefully, you could still choose to abruptly cancel a particular operation including adding clean up/rollback. e.g. `.takeUntil(action$.last())` or using `race()`. As you can imagine, seemingly no matter what library or pattern you use this sort of thing is a tough problem.

**Comment by matthewwithanm** [comment]
Yeah, that makes sense.

**Comment by jayphelps** [comment]
If someone want to create an RFC with a fleshed out proposal for a way to "kill" the root Epic via an API feel free but for now I believe it's good enough to say that with Epics, it becomes fairly easy to roll your own shutdown.

```js
const rootEpic = (action$, store) =>
  combineEpics(epic1, epic2)(action$, store)
    .takeUntil(action$.ofType(END_OF_ZE_WORLD));

// later
store.dispatch({ type: END_OF_ZE_WORLD });
```
