### ISSUE TITLE
Allow more flexible Actions (for example dispatch an array of Actions)

### ISSUE THREAD

**Issue by hackhat** [redux-observable/redux-observable#556]
For example I'm using batch actions (where you can dispatch 2 actions in one go), but redux-observable expect just one action, not an array of actions, and there is no way around it.

I'd need to be able to set this type:

`const epicMiddleware = createEpicMiddleware<AppAction, AppAction|AppAction[], IAppState, void>();`

**Comment by jameslaneconkling** [comment]
rather than use a batching middleware that expands the type definition of an action, which causes  all other middleware to update their action type definitions, you could use a different batching library that doesn't change the action shape, e.g. [redux-batched-actions](https://github.com/tshelburne/redux-batched-actions).

Using that library, you could do the following

```ts
export const pingEpic: Epic<Action, State> = (action$) => action$.pipe(
  ofType<Action, PinAction>(PING),
  delay(1000),
  map(() => batchActions([
    pong(),
    pong(),
  ]))
);
```

imho, a middleware should not change the action type definition, as this breaks the contract w/ every other middleware.

**Comment by Pappa** [comment]
@jameslaneconkling , maybe I'm missing the use case, but it seems it would be more straightforward to do something like:

```export const pingEpic: Epic<Action, State> = (action$) => action$.pipe(
  ofType<Action, PinAction>(PING),
  delay(1000),
  switchMap(() => of(pong(), pong())
);```

**Comment by hackhat** [comment]
But you will get 2 renders if you do that... With the lib I've mentioned above you get 1 render.

**Comment by jameslaneconkling** [comment]
@Pappa yes that would work fine, except as @hackhat has pointed out, the store will emit twice.  In most cases that is not an issue, but batching synchronous actions can be a useful performance optimization.

However, @hackhat , changing the Epic type signature isn't really an option.  redux-observable uses redux's dispatch internally to dispatch actions on the store, and the dispatch's type signature is not going to change (for context, see [this rejected PR](https://github.com/reduxjs/redux/pull/1813), **tl;dr** use `redux-batch-actions`).

But, w/ the exception of the dev tools displaying a single batchedAction, there shouldn't really be an issue using `redux-observable` w/ `redux-batch-actions`.

To emit multiple actions from an epic

```ts
export const pingEpic: Epic<Action, State> = (action$) => action$.pipe(
  ofType<Action, PinAction>(PING),
  delay(1000),
  map(() => batchActions([pong(), pong()]))
);
```

To initiate an epic from a batched action

```ts
type BatchAction<T> = {
  type: BatchActionType;
  payload: Action[];
  meta: { batch: true }
}

const isBatch = <T>(action: Action<T> | BatchAction<T>): action is BatchAction<T> =>
  (action as BatchAction<T>).meta && (action as BatchAction<T>).meta.batch

const ofType = <T extends Action, R extends T = T>(type: string) => filter<T | BatchAction<T>>((action) => (
  action.type === type || (
    isBatch(action) &&
    !!action.payload.find(({ type }) => type === type)
  )
));

export const pingEpic: Epic<Action, State> = (action$) => action$.pipe(
  ofType<Action, PongAction>(PING),
  delay(1000),
  map(() => batchActions([pong(), pong()]))
);
```

There's some acrobatics needed to get it to typecheck, but otherwise is pretty straightforward.

**Comment by hackhat** [comment]
@jameslaneconkling Yeah, filtering is fine, but if you need to read the action you filtered is not that easy. I'm not sure you can do it. This is what I'm talking about:

    export const pingEpic: Epic<Action, State> = (action$) => action$.pipe(
      ofType<Action, PongAction>(PING),
      // at this point the action can be a PongAction or a BatchAction containing a PongAction
      delay(1000),
      // Normally you just want to have a PongAction, not a BatchAction here
      tap((action:PongAction) => console.log(action))
    );

So an alternative ofType could be:

    const ofType = <T extends Action, R extends T = T>(type: string) => {
      return mergeMap<T | BatchAction<T>>((action) => {
        if(action.type === type){
          return of(action);
        }
        const innerActions = action.payload.filter(innerAction => innerAction.type === type);
        return from(innerActions);
      }
    };

(I didn't tested, just wrote now, so might not work)




Refactored your original code so is a bit more easy to read, took me a bit with all those typescript haha

    const ofType = <T extends Action, R extends T = T>(type: string) => {
      return filter<T | BatchAction<T>>((action) => {
        return action.type === type || (isBatch(action) && !!action.payload.find(({type}) => type === type))
      })
    };

**Comment by jameslaneconkling** [comment]
@hackhat , oh yeah, good point, in addition to filtering, `ofType` would need to unpack any matching batched actions.

I improved upon the typing a bit to get the following

```ts
type BatchAction<
  T extends Action,
  ActionType extends string = BatchActionType
> = Action<ActionType> & {
  payload: T[];
  meta: { batch: true }
}

const isBatch = <T extends Action>(action: T | BatchAction<T>): action is BatchAction<T> =>
  (action as BatchAction<T>).meta && (action as BatchAction<T>).meta.batch

export const ofType = <T extends Action, R extends T = T>(type: R["type"]) => (
  mergeMap<T | BatchAction<T>, R>((action) => {
    if (action.type === type){
      return of(action);
    } else if (isBatch(action)) {
      return from(action.payload.filter((action) => action.type === type));
    }

    return empty();
  })
);
```

**Comment by hackhat** [comment]
Yeah, that looks much better now. Thanks.

**Comment by hackhat** [comment]
I think is pretty useful to filter the actions in redux dev tools, I will re open this issue. Do you know how this could be solved?

**Comment by hackhat** [comment]
By the way `<T extends Action, R extends T = T>(type: R["type"])` can't be just `<T extends Action>(type: T["type"])`?

**Comment by jayphelps** [comment]
Coming in a bit late, my apologies!

> I think is pretty useful to filter the actions in redux dev tools, I will re open this issue. Do you know how this could be solved?

I think that would be upstream in the dev tools, rather than redux-observable yeah? Anything we should do?

**Comment by hackhat** [comment]
I don't know, what do you think is best?

**Comment by jayphelps** [comment]
@hackhat I think it's best to keep this as something you can optionally do either other addon middleware or helpers 👍

**Comment by hackhat** [comment]
Ok.
