### ISSUE TITLE
Provide mechanism to run process managers before reducers are hit

### ISSUE THREAD

**Issue by martypenner** [redux-observable/redux-observable#59]
Following up on [the comment here](https://github.com/redux-observable/redux-observable/pull/55#issuecomment-229109967):

I'm using [CouchDB](http://couchdb.apache.org/) (a document store) to sync data between client and server in react-native. The client database is considered the source of truth for all UI on the client. When a "data synced" event is emitted, I'm running a few queries against the db using Observable process managers, and emitting redux actions accordingly. The actions all follow the template of `UPDATE_X` with an array of X objects, where X might be users, for example. `redux-optimist` doesn't handle these types of actions well. Instead of `UPDATE_X` with an array of 5 objects, it prefers to see a sequence of 5 actions like `ADD_X`. That's not efficient enough for my needs, and I don't feel that library should add logic to handle list updates in that manner (too domain-specific IMO).

My way around it currently is to wrap all `UPDATE_X` action creators with a thunkservable that reverts all pending optimistic actions, runs the wrapped action, then replays the optimistic actions. I'm unable to do this with the current process managers because the reducers have been hit before the process manager runs.

**Comment by martypenner** [comment]
Actually, come to think of it, I could probably emit alternative redux actions that the reducers would ignore, then have process managers for those that would revert and replay appropriately. It's not ideal, but it would do the trick without muddying redux-observable.

**Comment by jayphelps** [comment]
That's a great start to an explanation--could you take it a bit further and provide some concrete examples of the the sequence of actions (with entire payload) that you're dealing with? We use a similar optimistic transaction based enhancer that is similar to redux-optimist, so I'm in general familiar with it and struggling to see where the issue is with `UPDATE_X` vs `ADD_X` style actions. These things are generally action content agnostic and really just record the action history and replay them on REVERT without the initial action that BEGIN's.

I'm not sure why you would be reverting them then reapplying them yourself though? That's the major odd part.

**Comment by martypenner** [comment]
> These things are generally action content agnostic

Agreed. After talking with the team a bit further, I'm realizing there's an error in my thinking. I'm really looking for more of a `MERGE_X` action, rather than `UPDATE_X`. I'll close this for now. Let me know if you'd still prefer I add the entire payload I'm dealing with for posterity.

**Comment by rajatvijay** [comment]
@jayphelps @martypenner 
So I am facing the same kind of issue. I am doing some analytics on the user activity.

The actual situation is: 
When the user lands on the URL, there are 5 items from which he can select of which I show one preselected(also using redux-observable to set some default value).
Then when the user selects the new item, I dispatch an action to set it in the store.
Now to track the item change I can use another epic to listen to the same action and make an ajax call to the tracking API but then I want the previous item too to be sent to the tracking API and I don't have it since actions run in the epics after they have been through the reducers, so the previous value has been replaced with the new value.

So is there a way I can get the action in the epic before they even hit the reducer?

**Comment by jayphelps** [comment]
@rajatvijay it's simply not possible to react to an action in an epic before it hits reducers. This is by design as it simplifies the pattern. I have not yet seen any situation in which receiving it before would have actually been the ideal choice.

I can try to help with your use case but unfortunately I can't follow--can you simplify and distill it down? It's possible some pseudo code would help too.

**Comment by gusvargas** [comment]
I think I understand the problem. The API that @rajatvijay is using takes a diff as a request payload, e.g., the newly selected item id *as well as* the previously selected id. The problem he's having is, when a new item is selected he's replacing the "item" state thus losing the ability for his api epic to create the diff request payload.

The first solution that comes to mind is to make your item-selecting-action-payload include the diff, e.g.,

```javascript
{
  type: "CHANGED_SELECTED_ITEM",
  payload: {
    from: 123,
    to: 456
  }
}
```

This action has enough information for your reducer to update the store *and* for your epic to hit the API. This, of course, means that in some redux container you'll have to pull from the current item in `mapStateToProps` so that it's available whenever you dispatch the change action.

```javascript
handleItemChange(nextItemId) {
  this.props.changeSelectedItem(
    this.props.currentSelectedItem,
    nextItemId
  );
}

// ... snip ...

connect(
  ({ selectedItemId }) => ({ currentSelectedItem: selectedItemId }),
  { changeSelectedItem }
)(MyComponent)
```

There is a bikeshedding opportunity here related to whether or not stuffing extra data in your payloads just to make epics happy is OK. Alternatively, you can just keep the previously selected item id in state.

```javascript
const trackChange = (action$, { getState }) =>
  action$
    .ofType("CHANGED_SELECTED_ITEM")
    .switchMap(({ payload }) =>
      Api.trackChange(
        getPreviouslySelectedItemId(getState()),
        payload.id
      )
      .map(finishItemChange)
    )
```

There is probably something clever you can do with Observables and closures in your epic so that the value that was previously selected is remembered, that way you don't have to maintain the prev value in the store.

```javascript
const trackChange = action$ => {
  return action$
    .ofType("CHANGED_SELECTED_ITEM") // first time this gets fired is with the preselected value when the app loads then subsequently on new changes
    .flatMap(({ payload: previousChangePayload }) =>
      action$
        .ofType("CHANGED_SELECTED_ITEM")
        .switchMap(({ payload }) => 
          Api.trackChange(
            previousChangePayload.id,
            payload.id
          )
          .map(finishItemChange)
        )
    )
}
```

I have no idea if ^^ actually works but hopefully it gets across what I had in mind.

**Comment by jeffbski** [comment]
If you would like to have access to the actions before (and after) they hit the reducer, you might want to check out redux-logic. It uses rxjs under the covers as well. I created it with those goals in mind.  https://github.com/jeffbski/redux-logic

**Comment by rajatvijay** [comment]
@jayphelps Thanks! but I think @gusvargas has resolved my issue.

> There is a bikeshedding opportunity here related to whether or not stuffing extra data in your payloads just to make epics happy is OK

So I would not say this is okay since analytics should entirely be a pluggable module and should not require any changes in the parent module in order to get plugged in.

> There is probably something clever you can do with Observables and closures in your epic so that the value that was previously selected is remembered, that way you don't have to maintain the prev value in the store.

This is something which has blown my mind away. I always knew RxJs has more to disclose and this is one of those many things. Tested and this works for my case. 

Just one more thing that needs clarification: 
So I am using `.onErrorResumeNext()` on all of my analytics Epics since if it fails it should not stop the actual working of the app. But in this case `.onErrorResumeNext()` should be used on the stream inside `.faltMap` or on the outer one will do?

**Comment by evertbouw** [comment]
Sounds like an opportunity for `pairwise`? Something like
```js
const trackChange = action$ => action$
    .ofType("CHANGED_SELECTED_ITEM")
    .pluck("payload", "id")
    .pairwise()
    .switchMap(([previousId, currentId]) => Api.trackChange(previousId, currentId)
        .map(finishItemChange));
```
