### ISSUE TITLE
Epics miss action emitted after `epicMiddleware.run()` depending on environment

### ISSUE THREAD

**Issue by tjfryan** [redux-observable/redux-observable#624]
**What is the current behavior?**
Depending on the environment when a store gets created and `epicMiddleware.run()` gets called, an action dispatched immediately after will get missed by the epics.  This seems to happen when `epicMiddleware.run()` occurs somewhere as a side effect of an observable using the queue scheduler (possibly others)

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**

https://stackblitz.com/edit/redux-observable-playground-emg4do?file=index.js

**What is the expected behavior?**
'TEST ACTION' will always get emitted to the epics regardless of where it's dispatched, as long as it's after `epicMiddleware.run()`. The programmer initializing the redux store and epic middleware should not have to be conscious of the code calling surrounding it.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
Happens with latest version. Bug found in an electron app, reproduced in chromium (stackblitz)

**Comment by BlackHole1** [comment]
I think this is not a problem. 
because `redux-observable` is calling `store.dispatch` internally.
`Redux-observable` does not override the store.dispatch method, It just calls the store.dispatch method internally.

**Comment by jayphelps** [comment]
Ah yes. Interesting find. This bug happens only inside a running task that was scheduled by the queueScheduler, it shouldn't ever happen any other time. What's happening is that the root epic is not yet subscribed because [that happens on the queueScheduler](https://github.com/redux-observable/redux-observable/blob/a3c09bc6aa5a8ee92a1ec665946748e8e4f2971c/src/createEpicMiddleware.js#L43) and because we're already inside a queueScheduler task that is still running, it waits until it returns before proceeding.

I'll see what I can do to mitigate this, perhaps removing the `subscribeOn(queueScheduler)` by moving some other things around.

Is it possible to describe how you hit this? That is, your real world use case that you came across? It might be hard to describe, but anything is helpful!

**Comment by BlackHole1** [comment]
Is there a practical difference between using queues here and not using them?

**Comment by jayphelps** [comment]
@BlackHole1 using them internally by redux-observable? Yep. It was added in 1.0.0 to support some recurring complaints people had, mostly related either actions emitted by epics at startup. e.g. [this case](https://github.com/redux-observable/redux-observable/blob/a3c09bc6aa5a8ee92a1ec665946748e8e4f2971c/test/createEpicMiddleware-spec.js#L256) and [this one](https://github.com/redux-observable/redux-observable/blob/a3c09bc6aa5a8ee92a1ec665946748e8e4f2971c/test/createEpicMiddleware-spec.js#L235)

**Comment by jayphelps** [comment]
I believe I have a working fix here #625

**Comment by BlackHole1** [comment]
Thank you, I think I understand.
Regarding the place you fixed, is it possible to use AsyncScheduler directly?

**Comment by jayphelps** [comment]
@BlackHole1 One thing: it uses QueueScheduler rather than AsyncScheduler. But unfortunately nope, QueueScheduler--capital Q, the constructor, not queueScheduler the singleton--is [not publicly exported by RxJS currently](https://github.com/ReactiveX/rxjs/blob/6661c796ea6f2918d4e6c0b68dfbecd4fbb7da74/src/index.ts#L17).

**Comment by BlackHole1** [comment]
Okay, I understand. Thank you for your answer

**Comment by tjfryan** [comment]
@jayphelps I was trying to upgrade the redux-observable version 1.0.0 on a codebase that used redux in unconventional ways in some of the more legacy parts of it, namely, having certain objects manage their state and side effects with it while interacting with other reduxy objects (instead of the suggested 1-per-app).

**Comment by jayphelps** [comment]
Fix landed in v1.1.0 could you confirm all is good now?

**Comment by tjfryan** [comment]
Yup! Thanks a ton
