### ISSUE TITLE
Async actions in constructors reveal another constructors what does not taken in count

### ISSUE THREAD

**Issue by Tarvald** [redux-observable/redux-observable#703]
Hi Again!
We are currently using the below setup for our store for SSR implementation.

https://pastebin.com/80tYcP5M

It was working flawlessly since we had to implement the last route to be fully rendered on the server. (seriously!)

On the server, we are doing two renders, by launching renderToString method twice.
First to launch all async actions from constructors, and second after shutdownEpics() will be resolved.

But we have one case where async action can reveal another constructor with extra async action that does not count during the first render.

Do you know how to deal with it?
I really looking forward to your opinion!

Best regards

**Comment by jayphelps** [comment]
Hello!

> But we have one case where async action can reveal another constructor with extra async action that does not count during the first render.

Hmm not sure what you're describing. If the issue is easily answered, I'm happy to help if I can. Though if it's custom and fairly complex, your best bet might be asking on the [Gitter chat](https://gitter.im/redux-observable/redux-observable?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or stackoverflow. Alternatively I offer custom support contracts for advanced support.

**Comment by Tarvald** [comment]
@jayphelps
Sorry for not being clear with my problem.
I meant that one of async action (from component constructor), change redux state what mount another component.
This newly mounted component also has a constructor with async action, unfortunately, shutdown$.complete() is launched before that mount and my server start rendering app.

So other words shutdown$.complete() is launched too early.

I took this approach somewhere from this repository and we built whole SSR conception based on it.

ps @jayphelps I saw your presentation a few years ago and since then I am using rx.js.
Thanks!

**Comment by jayphelps** [comment]
@Tarvald shoot sorry, the specifics are still too fuzzy for me to mentally picture what all you're referring to. If you want to put together an example demonstrating this issue I can run, that'd be ideal. If it helps, here's a stackblitz playground I often use as a starting point, but you can use anything: https://stackblitz.com/edit/redux-observable-typescript-playground?file=ping-pong.ts

Very generally looking at the "shutdown" mechanism code you provided and the general requirement of waiting for multiple concurrent and/or sequential async side effects, one approach to that is instead waiting for your root epic itself to complete, rather than waiting for the `shutdown$` Subject to complete. That means that all epics must naturally, eventually complete() when a shutdown signal is received. The caveat to this approach is that if you have a misbehaving epic that does not complete() in a timely fashion it would prevent your second pass from ever rendering. You'd want to mitigate this somewhat by adding a timeout() and handle that condition some what.

```js
// this all should be considered pseudo code as it's missing stuff
// it's just the general idea of what I'm saying and might contain issues
// e.g. it doesn't deal with the state$ observable yet

const actionsSubject = new Subject();

epicMiddleware.run((action$) => {
  const sub = action$.subscribe(actionsSubject);

  return rootEpic(actionsSubject.asObservable()).pipe(
    finalize(() => {
      sub.unsubscribe();
      // Re-render app again and stream to client
      renderTheAppSomehow();
    })
  );
});

renderTheAppSomehow();

// all epics listening to action$ should now naturally "shutdown"
// whenever their in-progress work (e.g. inside a mergeMap) has completed,
// assuming it does in fact complete.
actionsSubject.complete();
```

The problem I'm referring to generally speaking isn't specific to this approach, however it might be a bit more likely to happen on accident since it's pretty easy to not realize that an epic will not naturally complete() itself. That's why tests are very important. [Marble testing with virtualized time]](https://rxjs-dev.firebaseapp.com/guide/testing/marble-testing) is perfect for this.

**Comment by Tarvald** [comment]
I decided to put together an example demonstrating this issue you can run.
To be honest it is not an issue. but more our lack of rx.js knowledge. Sorry about that, we are still learning.

https://stackblitz.com/edit/redux-observable-typescript-playground-dvyejy

In general, inside of the example above the main problem is shutdown$()  does not wait for all actions from constructors to be finished.
I put some comments inside also, but code should be the best description.

Thank you, in advance for help!

**Comment by Tarvald** [comment]
I decided to put together an example demonstrating this issue you can run.
To be honest it is not an issue. but more our lack of rx.js knowledge. Sorry about that, we are still learning.

https://stackblitz.com/edit/redux-observable-typescript-playground-wr9rhu

In general, inside of the example above the main problem is shutdownEpics() does not wait for all actions from constructors to be finished.
I put some comments inside also, but code should be the best description.

Also, I thought to catch the situation (by the shape of redux state) where we should perform another async-actions round and wait to be completed again by shutdownEpics() method. But I have no idea if I am able to use shutdownEpics() method again and if it is not waste of extra renders and resources

Thank you, in advance for help!
