### ISSUE TITLE
Updating the RxJs version to the latest

### ISSUE THREAD

**Issue by glebpigulevsky** [redux-observable/redux-observable#767]
hi there. are there any plans to update dependencies? first of all RxJs as there are some conflicts between versions in the project.

for some reason, in my project redux-observable installs rxjs 7.4.0
<img width="436" alt="Screen Shot 2022-04-12 at 4 18 58 PM" src="https://user-images.githubusercontent.com/56892495/162961373-02c6b6eb-c6b7-438a-8dca-c65dd3313b69.png">

**Comment by jayphelps** [comment]
We only have it as [`^7.0.0`](https://github.com/redux-observable/redux-observable/blob/88d9631c1d052bedb442770dc7b833909db9c6ab/package.json#L71) so it shouldn't have any known issues with any v7. In this case it looks very likely just a simple of your lockfile doing the intentional (but sometimes very non-obvious) thing of making sure dependencies (and deps of deps, etc) do not change even though you might have duplicates in the tree. You might want to look into updating your lockfile via [`npm dedupe`](https://docs.npmjs.com/cli/v8/commands/npm-dedupe) but make sure to notice other changes it might make are safe. Lmk if I'm mistaken. Cheers.
