### ISSUE TITLE
TypeError: action$.ofType(...).delay is not a function

### ISSUE THREAD

**Issue by imranismail** [redux-observable/redux-observable#78]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
`TypeError: action$.ofType(...).delay is not a function`

whenever I pass an Epic to the middleware creator

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

Here's the configureStore

https://github.com/imranismail/test-redux-observable/blob/master/src/utils/configure-store.js

**What is the expected behavior?**

No error and middleware should be able to capture the actions

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

Chrome 51
OSX
redux-observable@0.7.2

**Comment by imranismail** [comment]
Fixed by just importing rxjs in my index file. This is weird, I thought ActionsObservable is already extending from Observable

**Comment by jayphelps** [comment]
`ActionsObservable` does indeed extend `Observable` but rxjs v5 does not automatically patch the `Observable` prototype with every operator. This is so that your builds can be smaller, only including what you use. There are several ways for you to import operators, depending on your needs/desires. See the rxjs docs for more info: https://github.com/ReactiveX/rxjs#installation-and-usage

If you do not wish for that behavior, you can inject every operator by placing this in one of your entry files like `index.js`:

```js
import 'rxjs/Rx';
```

**Comment by jayphelps** [comment]
This is something we probably wrongfully assumed people would already know from their Rx background--but it certainly doesn't hurt to mention it in the documentation. I'll do that!

**Comment by imranismail** [comment]
Makes perfect sense!

Thanks, I would prefer a smaller bundle size as well. Great job 👍

**Comment by jayphelps** [comment]
you're welcome! I added a note on this to the docs: http://redux-observable.js.org/docs/basics/Epics.html#a-basic-example and to the troubleshooting: http://redux-observable.js.org/docs/Troubleshooting.html#rxjs-operators-are-missing-eg-typeerror-actionoftypeswitchmap-is-not-a-function

**Comment by rgbkrk** [comment]
It would be great to add a note in http://jsbin.com/jexomi/edit?js,output, likely with a comment about the operator patching:

```js
// redux/modules/ping.js

// This example imports the entire RxJS library. When
// using this setup locally, you need to patch the operators
// used here:
// import 'rxjs/add/operator/delay';
// import 'rxjs/add/operator/mapTo';

const PING = 'PING';
const PONG = 'PONG';

const ping = () => ({ type: PING });

const pingEpic = action$ =>
  action$.ofType(PING)
    .delay(1000) // Asynchronously wait 1000ms then continue
    .mapTo({ type: PONG });

...
```

**Comment by jayphelps** [comment]
@rgbkrk Great point. Those bins that are not displayed inline with the docs lack that context. I'll need to wordsmith a bit cause I don't want to recommend one particular pattern of using operators over the others. Perhaps I'll link out to a new page that addresses the multiple ways, similar to what the [RxJS docs do](https://github.com/ReactiveX/rxjs#installation-and-usage) but in in the context of Epics.

I had originally felt that anyone using redux-observable should already be familiar with RxJS's operator patching but it turns out a lot of people's experience with it was importing all of RxJS via `import Rx from 'rxjs'` so they never noticed that it has this ability that we _let you_ take advantage of, if you want.

**Comment by jayphelps** [comment]
Added this disclaimer to the top of all the JSBins in the README and UsageWithUIFrameworks.md.

```js
/**
 * IMPORTANT ***************************************************************
 * 
 * This example uses the global version of RxJS that includes ALL operators.
 * Inside your app, you will likely need to import the operators you use or
 * import all of them in your index.js entry file.
 * 
 * Learn more about this: http://goo.gl/4ZlYeC
 */
```

**Comment by rgbkrk** [comment]
> I had originally felt that anyone using redux-observable should already be familiar with RxJS's operator patching but it turns out a lot of people's experience with it was importing all of RxJS via import Rx from 'rxjs' so they never noticed that it has this ability that we let you take advantage of, if you want.

Since we've been using RxJS in an Electron app, we gleefully ignored the operator patching since we already have it all on disk anyways. For a bunch of folks, this has been their first introduction to RxJS so we (nteract) may be doing a disservice to them. It's probably a little bit worse than that because we have libraries that return observables as well, with an expectation that they have certain operators on them.

**Comment by rgbkrk** [comment]
That disclaimer is perfect!

**Comment by craigcosmo** [comment]
The 
```js
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/mapTo';
```
should be in the examples as well

**Comment by jayphelps** [comment]
@craigcosmo we intentionally do not take any opinions on how you should import your operators because there are several ways and people tend to take our suggestions as if they are meant as best practices. We also assume you're already familiar with RxJS

![image](https://cloud.githubusercontent.com/assets/762949/22386391/b5a0d2ce-e48b-11e6-943d-a0cf098207ff.png)

**Comment by craigcosmo** [comment]
It's just javascript as far I know. The redux people import redux in their example. The react people also do that. It's hardly best practice, it's what you need to do to make it work.

But I think you misunderstand my suggestion. I meant, the example should show how it import the modules it uses, regardless the way.

And I just check one of the redux-observerable examples again, I see you guys put the import `rxjs` in the global index file. Which is fine.  But it would be instant understood for me if it was imported in the epics.

**Comment by jayphelps** [comment]
@craigcosmo sorry about that. If I was confused, I still am. 🙁 There are [numerous ways](https://github.com/ReactiveX/rxjs#es6-via-npm) to import your operators. If used _any_ of them in the docs, we would be implicitly _suggesting_ you do it that way. Or worse, people would blame us for their bundles being large (because they imported all operators) or they would blame us that using RxJS is annoying (because they import operators one by one). RxJS gives you the choice, but you have to _know_ RxJS to know that's a choice, and using redux-observable without first knowing RxJS isn't something we currently recommend.

**Comment by myquery** [comment]
Am new to redux, and my first encounter landed me in using epic, but i have one problem connectng epic with my store in my app module, am using angular.
**The Action Creators**
`//this is action creator defined inside a class
static LIST_ALL_COMPETITIONS = 'LIST_ALL_COMPETITIONS';
listAllCompetition(payload : ICompetition[]) : AnyAction {
  return this.ngRedux.dispatch(
    { type: SessionActions.LIST_ALL_COMPETITIONS, 
      payload});
};`

> i would want this action dispatched if a user hit  my url in the browser, kind of fetching the data from the server, so  i would probably call this in my ngOnit or use a resolver in the route path.

**The Reducer Function**
>My reducer function will take an initial state that comprises of the different endpoint that will prefetch which of course has the same structure with the remote data which i enforced by creating each interface for each endpoint.

` export const initialState:IAppState = {
    competitions: [],
    matches:[],
    teams : [],
    standing: [],
    players:[]

  }

  export function FootballReducer(state: IAppState = initialState, action){
      switch(action.type){
          case ActionTypes.ListCompetitionSuccess:
              return{
                  ...state, 
                  competitions: action.payload
              }
      
      }

      return state;
  }`

> if am able to setup epic correctly, it suppose the intercept the actions coming in from the component, do the network call and return an action containing the payload of the fetched result

`constructor(private http: HttpClient, private service : FootballStoreService, private action : SessionActions ) { }
  listAllCompetitions  = (action$) : AnyAction => {
     // do(val => console.log(val))
    return action$.pipe(
        ofType(SessionActions.LIST_ALL_COMPETITIONS),
      mergeMap(() => {
        return this.service.listAllCompetition()
          .map(result => {
              return this.action.listAllCompetition(result)
          })
          .catch(error => Observable.of({
            type: SessionActions.ERROR_LIST
          }));
        }))
   }`

> the issue now is configuring epic to create a store at my app module. another thing am unsure of is whether an setting up epic correctly interm of my reducer and action, i need explanations on this.

**the app module congif**

`export class AppModule {
  
  constructor(private ngRedux : NgRedux<IAppState>, private epic : EpicServiceService){
    const epicActiion = createEpicMiddleware(this.epic.listAllCompetitions(this is where the problem is, bringing in my epic funtions here))

    // const middleWare = [createEpicMiddleware(SessionActions.LIST_ALL_COMPETITIONS)];
      ngRedux.configureStore(
      FootballReducer, 
      initialState
      
      )
  }
}`

> my problem is that the createmiddleWare functions needs a action type and i don't know how to feed it that argument.

Setting up the store including epic middleware shouldn't be made too complicated, redux on its own is already confusing, if somebody is able to learn what an actions is, and where the reducer functions comes in, bringing in epic as a tool that will aid side effects should be made easy to integrate. so pls with the latest release of RxJS library, point me to a link that can detail how to work with redux and observable using epic as it relate to my reducers and actions. but better still somebody here can guide with code snippets on the best practice.
