### ISSUE TITLE
Update peer dependencies to include `redux@5` (currently beta)

### ISSUE THREAD

**Issue by markerikson** [redux-observable/redux-observable#784]
We're hoping to release the full wave of Redux package major versions by the first week of December.  That includes RTK 2.0, and Redux core 5.0.

I see that `redux-observable` currently lists `"redux": ">=4 <5"` as a peer dep. Could you put out a beta of some kind that ups the dep to `"redux": "^5.0.0-beta.0"`, and test things on your end?

**Comment by jayphelps** [comment]
@markerikson Hey duder. Thanks for the heads up, but I don't have a lot of cycles these days. Redux Observable is in maintenance mode as there hasn't been any notable need for changes since it's a relatively simple library.

That said, once v5 of redux is in RC or finalized I can make some time to cut a release to support the new version as long as any changes necessary are simple.

**Comment by markerikson** [comment]
Gotcha. Yeah, I'm actually hoping to cut `-rc` releases of everything either this afternoon or later this week.  I'll let you know when those are out.

The most likely change that might cause issues, without looking at the actual code, is that the Redux `Middleware` type now defaults to using a new `UnknownAction` type as the default for `action`, instead of the existing `AnyAction` type.  (basically, "we have no idea what fields exist in your action object, you should type-guard to figure that out for yourself instead of just accessing `action.whatever` and getting `any` back.)  Not immediately sure how much of an actual impact that might have here.

Thank you for the fast response!

**Comment by evertbouw** [comment]
I have time to make code changes if necessary, but I don't have any actual apps to test it on.

**Comment by evertbouw** [comment]
@jayphelps can you publish a release candidate?
