### ISSUE TITLE
Request to move ActionsObservable into a separate module

### ISSUE THREAD

**Issue by MikeRyanDev** [redux-observable/redux-observable#95]
[@ngrx/effects](https://github.com/ngrx/effects) and [redux-observable](https://github.com/redux-observable/redux-observable) both have separate implementations of an actions observable that includes a custom operator for filtering actions by type (see `StateUpdates#whenAction` in @ngrx/effects and `ActionsObservable#ofType` in redux-observable).

It would be great if redux-observable's `ActionsObservable` could be moved into a separate module so that both of these libraries can share a common implementation.

cc @blesh

**Comment by jayphelps** [comment]
Are you looking for _our_ code to be moved mostly as-is or is there debate around the subtle differences between the implementation of `StateUpdates` vs `ActionsObservable`?

**Comment by MikeRyan52** [comment]
Looking for it to be moved mostly as-is. Only request is that instead of using the `Action` interface exported from Redux's typings you use a custom type that satisfies both Redux's and ngrx/store's `Action` interface. This should suffice:

```ts
interface Action {
  type: any;
}
```

**Comment by jayphelps** [comment]
That seems doable 💃

Since redux-observable and `@ngrx/effects` are mostly the same thing, is there anything else we can do to reduce redundancy? Clearly I'm biased on this, but I've mentioned to @robwormald multiple times how great it would be if ngrx just used redux...then all the crazy amount of [libraries](https://www.npmjs.com/search?q=redux), extensions, and documentation would "just work™".

I can't recall any notable reason for ngrx to not use it other than for under-the-hood RxJS purity. It just feels so silly to me that ngrx and ng2-redux have to independently do the same thing.

**Comment by jayphelps** [comment]
That seems doable 💃

Since redux-observable and `@ngrx/effects` are mostly the same thing, is there anything else we can do to reduce redundancy? Clearly I'm biased on this, but I've mentioned to @robwormald multiple times how great it would be if ngrx just used redux...then all the crazy amount of [libraries](https://www.npmjs.com/search?q=redux), extensions, and documentation would "just work™".

I can't recall any notable reason for ngrx to not use it other than for under-the-hood RxJS purity. It just feels so silly to me that ngrx and ng2-redux have to independently do the same thing.

**Comment by SethDavenport** [comment]
On the  ng2-redux front, compatibility with the redux community is important to us.  That said, it's perfectly reasonable for both solutions to pursue their respective priorities. 

However for the sake of community I'm interested in helping with alignment where it makes sense.

**Comment by MikeRyan52** [comment]
We want to support more of Redux's ecosystem going forward while still providing a great Angular 2 developer experience and remaining respectful of the community that's built on top of ngrx. Our best way of doing this is incrementally and this change would be a good step towards aligning ngrx/effects with redux-observable.

**Comment by SethDavenport** [comment]
While we talking about actions, thoughts on [flux standard actions] (https://github.com/acdlite/flux-standard-action)?

As in, the shared interface might be 

```typescript
{
  type: string;
  payload?: any;
  error?: boolean;
}
```

**Comment by jayphelps** [comment]
@SethDavenport I use it personally and try to do so consistently the docs (lmk if not) but other than that I do not think it's grown enough in popularity to force that type on people, especially if redux-observable does not provide any features that require it. Though since they'd be optional fields, I don't know if _force_ is the right word--except `error?: boolean` does force `error` to be a bool if its provided.

**Comment by SethDavenport** [comment]
Yeah fair enough. It's annoying to have to declare a subinterface in every app but I get that it's an interface change that could have subtle detrimental effects on existing users.

**Comment by jayphelps** [comment]
@SethDavenport you should bug them to add typings or merge this PR https://github.com/acdlite/flux-standard-action/pull/33 that does.

**Comment by MikeRyan52** [comment]
One more request: I am looking to make this change for Angular 2 RC 5. It looks like there _might_ be a chance Angular 2 RC 5 will still have a locked dependency on rxjs@5.0.0-beta.7. If possible it would be great if redux-observable/actions-observable could support ^rxjs@5.0.0-beta.7.

From a cursory glance it doesn't seem as if this will have any impact on the implementation of `ActionsObservable`, just the module's dependencies.

**Comment by blesh** [comment]
It's strange to me that ng2 would be stuck at rxjs 5b7... they should be on the latest. There are a lot of bugs that have been fixed since 7.

**Comment by MikeRyan52** [comment]
@blesh I misspoke, they are actually on beta 6, not beta 7. 

Angular 2 RC5 has been released and retains a locked dependency on 5.0.0-beta.6

**Comment by blesh** [comment]
Yeah, that's weird, I'm going to figure out why that is.

**Comment by blesh** [comment]
@MikeRyan52 actually as of RxJS 5.0.0-beta.11 I'm told they'll be moving up.

**Comment by MikeRyan52** [comment]
@blesh Thanks, hopefully that makes it into RC 6 within the next couple of weeks.

**Comment by Bretto** [comment]
Any progress on this front ?

**Comment by jayphelps** [comment]
@bretto nope

**Comment by MikeRyanDev** [comment]
With pipeable operators I don't really see a benefit in this these days. It would be neat to maybe share the implementation and types for the `ofType` operator (as it will likely get more complex with TypeScript 2.8) but even then it is a really small amount of code.
